INSERT INTO aircompanies (name) VALUES
	('Hoeger LLC'),
	('Orn-Schumm'),
	('Wolf-Howell'),
	('Stamm-Fahey'),
	('Ankunding-McClure'),
	('Dooley Group'),
	('Hermiston and Sons'),
	('Kilback Inc'),
	('Ondricka and Sons'),
	('Connelly Inc'),
	('Stroman-Barton'),
	('Lang, Kreiger and Altenwerth'),
	('Haley, Bogisich and Koch'),
	('Nicolas, DuBuque and Wunsch'),
	('Lynch-Doyle'),
	('Turner, Grimes and Bruen'),
	('Hintz, Dietrich and Fahey'),
	('Brown, Lehner and Bernhard'),
	('Kassulke Group'),
	('Bartoletti Inc'),
	('Fahey, Collins and Bartell'),
	('Mitchell, Blanda and Marquardt'),
	('Reichel-Boyer'),
	('Towne and Sons'),
	('Beer, Kuhn and Kassulke'),
	('Gutmann, Mann and Mertz'),
	('Bartoletti-Rogahn'),
	('Buckridge, McDermott and Beatty'),
	('Heaney-Lesch'),
	('Zemlak Group'),
	('Gottlieb-Kassulke'),
	('Tremblay-Greenfelder'),
	('Aufderhar, Hills and Brekke'),
	('Konopelski and Sons'),
	('Daugherty-Hagenes'),
	('Jones-Tromp'),
	('Goldner, Gusikowski and Reichert'),
	('Bashirian-Corwin'),
	('Gislason LLC'),
	('Bergstrom-Cartwright'),
	('Block and Sons'),
	('Hahn, Stoltenberg and Cremin'),
	('Shanahan LLC'),
	('Bradtke, Lesch and Lowe'),
	('Hoeger, Sporer and Ledner'),
	('Treutel, Hackett and Ritchie'),
	('Thiel and Sons'),
	('Sporer-Buckridge'),
	('Willms Group'),
	('Crooks, Harvey and Keebler'),
	('Lueilwitz and Sons'),
	('Wiza Group'),
	('Morissette, Fadel and Luettgen'),
	('Oberbrunner-Toy'),
	('Gottlieb-Gutkowski'),
	('Crooks-Douglas'),
	('Stracke, Mayert and Hettinger'),
	('Frami Group'),
	('Bins Group'),
	('Jerde, Pfeffer and Dibbert'),
	('Ebert Group'),
	('Harvey-Kuvalis'),
	('Dickinson-Nikolaus'),
	('Hackett, Murphy and Russel'),
	('Prohaska Group'),
	('Cremin, Bayer and Zulauf'),
	('Quitzon LLC'),
	('Daniel Inc'),
	('Pouros-Hand'),
	('Pfeffer Inc'),
	('Klocko, Gislason and Hane'),
	('Herzog, Skiles and Willms'),
	('Kuphal, Lakin and Reinger'),
	('Williamson-Green'),
	('Hahn-Pfeffer'),
	('Abernathy and Sons'),
	('Kilback, Lueilwitz and Hessel'),
	('Muller-Kling'),
	('Senger LLC'),
	('Donnelly-Osinski'),
	('Legros-Johns'),
	('Abshire Inc'),
	('Deckow-Feest'),
	('Paucek-Skiles'),
	('Jaskolski-Renner'),
	('Flatley and Sons'),
	('Mayert LLC'),
	('Hane, Feest and Price'),
	('Erdman-Langworth'),
	('Hahn-Lakin'),
	('Larson, Waters and DuBuque'),
	('Breitenberg Inc'),
	('OKeefe, Schaden and Ziemann'),
	('Senger LLC'),
	('Turner Inc'),
	('Daugherty, Rath and Jenkins'),
	('Walker-Crist'),
	('Hoeger and Sons'),
	('Medhurst Inc'),
	('Zboncak LLC'),
	('Prosacco-Ledner');
INSERT INTO countries (name) VALUES
	('Anguilla'),
	('Belize'),
	('United Kingdom'),
	('Antarctica (the territory South of 60 deg S)'),
	('Nigeria'),
	('South Georgia and the South Sandwich Islands'),
	('Bulgaria'),
	('Georgia'),
	('Costa Rica'),
	('Democratic Peoples Republic of Korea'),
	('Canada'),
	('Guatemala'),
	('Ecuador'),
	('Zimbabwe'),
	('Tonga'),
	('Czech Republic'),
	('Canada'),
	('Trinidad and Tobago'),
	('Barbados'),
	('Norfolk Island'),
	('Solomon Islands'),
	('Ecuador'),
	('Botswana'),
	('Afghanistan'),
	('Turkey'),
	('Bahamas'),
	('Cambodia'),
	('Taiwan'),
	('Belize'),
	('Samoa'),
	('Peru'),
	('Brazil'),
	('Guinea'),
	('Palau'),
	('Qatar'),
	('Slovenia'),
	('Egypt'),
	('Maldives'),
	('Italy'),
	('Romania'),
	('Venezuela'),
	('Swaziland'),
	('Sri Lanka'),
	('Ethiopia'),
	('Turkmenistan'),
	('Kazakhstan'),
	('United Kingdom'),
	('Brunei Darussalam'),
	('Timor-Leste'),
	('Somalia'),
	('Cuba'),
	('Nauru'),
	('Albania'),
	('Turkey'),
	('Kuwait'),
	('Sao Tome and Principe'),
	('Gabon'),
	('Marshall Islands'),
	('French Polynesia'),
	('New Zealand'),
	('Netherlands'),
	('France'),
	('South Georgia and the South Sandwich Islands'),
	('French Guiana'),
	('Guadeloupe'),
	('Burundi'),
	('Estonia'),
	('Malta'),
	('Switzerland'),
	('Reunion'),
	('Bouvet Island (Bouvetoya)'),
	('Maldives'),
	('Algeria'),
	('Maldives'),
	('Heard Island and McDonald Islands'),
	('Thailand'),
	('Cayman Islands'),
	('Mauritius'),
	('Germany'),
	('Italy'),
	('Azerbaijan'),
	('Canada'),
	('Congo'),
	('Isle of Man'),
	('Canada'),
	('Somalia'),
	('Malaysia'),
	('Bangladesh'),
	('French Polynesia'),
	('Saint Vincent and the Grenadines'),
	('Lithuania'),
	('Malawi'),
	('Somalia'),
	('Burkina Faso'),
	('Sao Tome and Principe'),
	('Niue'),
	('Isle of Man'),
	('Tunisia'),
	('Malawi'),
	('China'),
	('Pouros-Johns');
INSERT INTO cities (name, country_id) VALUES
	('South Carmeliaport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Dalia', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Sonnyhaven', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Haleyport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Twannaburgh', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Tommyport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Paucekburgh', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Melvinside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Ermelindaville', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Georgettastad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Lylemouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Fredport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Abernathyport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Kristelberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Bayerberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Ajamouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Tommiefort', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Deandre', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Jeffton', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Thanh', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Davetown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Leighshire', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Gavinport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Benjaminberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Kevin', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Tijuana', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Refugio', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Theronport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Meliaton', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Esperanza', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Zboncakland', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Wolftown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Karenamouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Nickchester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Ervinmouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Chase', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Collierville', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Samchester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Tommyside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Dustyville', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Jana', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Bud', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Johnie', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Walter', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Gutkowskiport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Judsonside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Dylantown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Lloydshire', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Russellport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Abernathyberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Krajcikstad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Wintheiserport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Muiville', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Martinside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Lerachester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North James', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Ariane', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Pablo', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Connellyton', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Wittingberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Raymon', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Klockoborough', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Aufderharberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Antonyfurt', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Gregg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Alla', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Willard', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Warnerstad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Marquardtside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Johnsport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Krajcikmouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Agripinaside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Bernardo', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Faviolaberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Bradtkeport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Lucioview', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Bethelberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Timmyshire', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Cinderella', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Winfredland', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Ellis', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Heribertotown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Christen', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Victor', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Hobert', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Tora', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Kilbackview', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Sammie', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Beckiville', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Justaport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Wolffberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Antonioport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Leaside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Lamont', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Leoniahaven', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Clarine', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Manualshire', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Kerryshire', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Rueckertown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Larhonda', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Mayer, Padberg and Senger', (SELECT id FROM countries ORDER BY random() LIMIT 1));
INSERT INTO airports (name, city_id) VALUES
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tampa International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Orlando International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('LaGuardia Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('George Bush Intercontinental Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Portland International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ronald Reagan Washington National Airport**', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Logan International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Portland International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('LaGuardia Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dulles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Philadelphia International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Orlando International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('George Bush Intercontinental Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Philadelphia International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hartsfield Jackson Atlanta International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Logan International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Daniel K. Inouye International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Portland International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Charlotte Douglas International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Harry Reid International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Salt Lake City International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Phoenix Sky Harbor International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Harry Reid International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Francisco International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Logan International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Newark Liberty International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tampa International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Minneapolis Saint Paul International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('John F. Kennedy International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('George Bush Intercontinental Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Denver International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Denver International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Phoenix Sky Harbor International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tampa International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Denver International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Newark Liberty International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Francisco International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Logan International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Midway International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Newark Liberty International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('John F. Kennedy International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tampa International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Diego International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Midway International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('George Bush Intercontinental Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Denver International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Seattle Tacoma International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Detroit Metropolitan Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('John F. Kennedy International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hartsfield Jackson Atlanta International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Daniel K. Inouye International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('LaGuardia Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('LaGuardia Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hartsfield Jackson Atlanta International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Seattle Tacoma International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('OHare International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('George Bush Intercontinental Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Midway International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('George Bush Intercontinental Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Newark Liberty International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('LaGuardia Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Orlando International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tampa International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Phoenix Sky Harbor International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Logan International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dulles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dulles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Minneapolis Saint Paul International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('John F. Kennedy International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Philadelphia International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Seattle Tacoma International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Logan International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Newark Liberty International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Francisco International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Portland International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Salt Lake City International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Denver International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Diego International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('LaGuardia Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Minneapolis Saint Paul International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1));
INSERT INTO hotels (name, has_pool, number_of_stars, cleaning_included, price_for_a_person, city_id) VALUES
	('Rev. Maribeth Little Towne', 'false', 4, 'true', 140, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ramiro Bauch Baumbach', 'true', 3, 'true', 46, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Salvador Lind Schultz', 'false', 3, 'false', 28, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Markus Rath Bogisich', 'false', 5, 'true', 65, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Yevette Ortiz Conn', 'true', 3, 'false', 80, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mi Gutkowski Leffler', 'true', 2, 'true', 94, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Saul Heaney Lowe LLD', 'true', 5, 'false', 7, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Min Moen Harber', 'false', 3, 'false', 1, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Malka Fahey Bosco', 'false', 2, 'false', 37, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Emil Schroeder Renner', 'true', 5, 'false', 214, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Haywood Wunsch Conn', 'false', 2, 'false', 70, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tonia Murphy Bayer', 'false', 1, 'false', 2, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Yu Champlin Cartwright', 'true', 1, 'false', 14, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ms. Nathanael Toy Tromp', 'false', 4, 'true', 15, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Amb. Kayla Goodwin Crist', 'true', 1, 'false', 9, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Pres. Fidel Carroll Beatty', 'true', 3, 'false', 28, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ms. Ramiro Greenfelder Sawayn', 'false', 1, 'false', 10, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Lucius Murray Fritsch', 'true', 5, 'false', 162, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Reginald Larkin Langosh', 'true', 4, 'true', 103, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Nathanael Kulas Trantow IV', 'false', 4, 'true', 121, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Amb. Ute Jacobs Stehr', 'true', 3, 'false', 53, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Amb. Darwin Kunde Ward', 'false', 2, 'true', 49, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fr. Deeann Nicolas Aufderhar', 'false', 3, 'false', 132, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Burl Torp Ratke', 'false', 5, 'true', 67, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Danilo Ziemann Strosin CPA', 'true', 3, 'true', 85, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Kurt Wintheiser Gislason Jr.', 'false', 2, 'false', 73, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Amee Glover Schinner LLD', 'false', 1, 'true', 9, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Shaunda Reichel Nicolas Esq.', 'true', 3, 'false', 20, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Wally Hermann Ward', 'false', 1, 'true', 38, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Alden Schuppe Klein', 'false', 3, 'false', 66, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mario OConnell Bosco II', 'true', 4, 'true', 52, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Grover Schimmel Kutch', 'true', 1, 'false', 25, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tam Powlowski Franecki', 'true', 4, 'true', 36, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Cherri Miller Daugherty', 'true', 4, 'false', 143, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Monroe Bauch Krajcik', 'false', 2, 'true', 48, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Prof. Rhiannon Romaguera Schiller', 'false', 1, 'true', 23, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Jessika Sipes Breitenberg LLD', 'true', 2, 'false', 31, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Virgil Bayer Mertz', 'true', 2, 'false', 39, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hosea Bartell Corwin', 'true', 2, 'true', 71, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Gov. Lucina McGlynn Okuneva', 'true', 3, 'false', 53, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Leota Walker Lakin CPA', 'false', 5, 'false', 48, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ahmad Jacobson Turner', 'false', 1, 'true', 32, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Rosana Altenwerth Simonis', 'true', 5, 'true', 20, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Pres. Darron Luettgen Tillman', 'false', 5, 'false', 79, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Kerrie Schoen Boyle VM', 'false', 5, 'false', 182, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Jonathan Ratke Tromp', 'false', 3, 'false', 97, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Warner Ortiz Christiansen', 'false', 1, 'true', 23, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Pres. Lonny Lueilwitz Torp', 'false', 4, 'true', 185, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mamie Toy Bergnaum', 'true', 4, 'false', 149, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Alton Hills Corkery', 'true', 5, 'true', 4, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Trinidad Lind Schroeder', 'true', 1, 'false', 30, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Huey Fritsch Hammes', 'false', 1, 'false', 49, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Jeanie Moore Brown', 'true', 1, 'true', 47, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Kareem Bayer Lebsack', 'false', 3, 'true', 79, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Virgina Mohr Bailey', 'false', 4, 'true', 189, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Karine Price Collier', 'true', 5, 'true', 65, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Julio Stoltenberg Prosacco', 'false', 4, 'false', 153, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Shawnta Hamill Abernathy', 'false', 5, 'false', 155, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Noble Emmerich Mante DC', 'true', 3, 'true', 75, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Msgr. Yolando Smitham Schaden', 'false', 3, 'true', 44, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fr. Bradly Grady Bauch', 'true', 2, 'true', 29, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Rev. Berry Gottlieb Emard', 'true', 4, 'true', 111, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Josh Gorczany Lakin', 'true', 1, 'false', 38, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Gov. Damon Schamberger Aufderhar', 'false', 5, 'false', 39, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dominick Schamberger Kutch', 'false', 4, 'true', 111, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Vicente Grant Schoen', 'false', 2, 'false', 36, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Glennis Block Bednar', 'false', 1, 'false', 24, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Doyle OKon Aufderhar', 'true', 5, 'false', 209, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Rupert Breitenberg Schinner', 'false', 4, 'false', 167, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Royce McDermott Marvin', 'false', 2, 'true', 10, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Milissa Schimmel Feest', 'true', 4, 'false', 11, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Kimberely Gusikowski Walter', 'false', 2, 'false', 44, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ferdinand Johnston Heathcote', 'true', 2, 'false', 97, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Richard Kovacek Cartwright', 'true', 3, 'false', 138, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Alba Mante Dicki', 'true', 1, 'true', 17, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Martina Schuppe Wehner', 'true', 4, 'false', 69, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dr. Reed Wunsch Koch', 'false', 5, 'false', 6, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mr. Ciara Crist Trantow', 'true', 4, 'false', 39, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tai Smith Schmitt', 'false', 2, 'false', 20, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Venita Monahan Ullrich', 'false', 2, 'false', 22, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mrs. Fritz Jenkins Metz', 'false', 1, 'false', 16, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Sanford Fay Rice', 'false', 1, 'true', 18, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Rashad Ullrich Dickinson', 'false', 5, 'true', 18, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Palmer Wisozk Langworth', 'true', 2, 'true', 65, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Lakia Stroman Rogahn', 'true', 2, 'true', 85, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Melody Schinner Hane', 'true', 3, 'true', 3, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Adrien Grimes Nitzsche', 'false', 5, 'false', 228, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Sheba Medhurst Buckridge', 'false', 1, 'false', 29, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Alphonso Deckow Sanford', 'false', 2, 'false', 98, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Sen. Abel Gutmann Cormier', 'true', 3, 'false', 103, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Arnulfo Goldner Funk Ret.', 'true', 5, 'false', 48, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Cecil Kuphal Graham', 'true', 2, 'true', 8, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Gwyneth Rempel Feil', 'true', 5, 'true', 211, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Elliot Hammes Rutherford IV', 'true', 4, 'true', 13, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Quintin Heller Powlowski', 'false', 1, 'false', 41, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Man Beahan Lang', 'false', 5, 'true', 53, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mrs. Kyle Ryan Streich', 'true', 3, 'false', 7, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dr. Darron Gibson Bauch', 'true', 4, 'false', 141, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Kip Baumbach Osinski III', 'true', 2, 'false', 95, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Franklin Satterfield Jacobi', 'false', 5, 'true', 15, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Page Spencer Swift Ret.', 'true', 3, 'true', 141, (SELECT id FROM cities ORDER BY random() LIMIT 1));
INSERT INTO clients (full_name, phone, birthday_date, has_member_card) VALUES
	('Katelin Spinka Mueller', '+213 682.943.1345', '1988-10-24', 'false'),
	('Xavier Leannon Runte', '+41 1-989-313-2003', '1959-11-22', 'true'),
	('Glen Kshlerin Doyle DO', '+381 1-126-558-1599 x59287', '1992-06-05', 'false'),
	('Benito Auer Osinski', '+92 187-127-4746 x63472', '1974-02-12', 'true'),
	('Joesph Bins OConner', '+676 709.908.7229 x549', '2004-06-03', 'true'),
	('Wyatt Kozey Weimann', '+501 (730) 803-0455 x06047', '1993-03-06', 'true'),
	('Darin Hermiston Erdman', '+681 1-855-590-8555 x943', '1968-11-19', 'false'),
	('Christia Botsford Schoen', '+227 207.514.7703 x805', '1995-11-21', 'false'),
	('Noe Kiehn Zemlak', '+221 707.058.6231 x0137', '1970-04-06', 'false'),
	('Eugene Roberts Casper', '+599 (166) 283-5328', '1985-07-13', 'true'),
	('Mrs. Rayford Stiedemann Stamm', '+685 1-851-412-6250 x65204', '1997-04-10', 'false'),
	('Ward Reinger Ziemann MD', '+291 (416) 995-2238', '1992-05-22', 'false'),
	('Yael Koepp Grant', '+1-876 411-483-4548 x99818', '2001-12-21', 'false'),
	('Fr. Courtney Weber Bahringer', '+1-939 (676) 923-2747 x0593', '1986-04-03', 'true'),
	('Enrique Langosh Wilkinson', '+597 432-595-3606 x4727', '1959-01-21', 'false'),
	('Tynisha Bruen Conroy', '+767 488.254.3260', '1996-07-05', 'false'),
	('Alda Green Champlin', '+387 (915) 487-2820', '1972-11-12', 'true'),
	('Claude Hirthe Mitchell', '+20 (928) 101-4323', '1980-04-04', 'false'),
	('Errol Bernier Jacobson', '+688 1-495-183-3560 x942', '1972-05-26', 'false'),
	('Mose Bernier Hettinger', '+7-7 (855) 450-5687', '1979-08-20', 'true'),
	('Erwin Feeney Willms VM', '+692 770.803.0978 x761', '1966-04-17', 'true'),
	('Wade Koch Walsh', '+226 868.171.9103', '1960-12-10', 'true'),
	('Kirk Konopelski Littel', '+224 1-380-158-0991 x3346', '1963-11-22', 'true'),
	('Prof. Whitney Carroll Hilpert', '+681 699-536-6666 x4092', '1961-12-25', 'false'),
	('Erik Rath Kilback', '+670 1-914-876-0496 x8768', '1985-12-23', 'true'),
	('Gemma Stamm Hammes', '+595 1-884-851-3881 x007', '1969-02-19', 'true'),
	('Isidra Bogan Reichel', '+260 799.383.3420', '1973-02-18', 'false'),
	('Gov. Rickie Graham Rolfson', '+33 1-494-337-7018 x0426', '1965-08-30', 'false'),
	('Clifford Vandervort Zemlak', '+500 (968) 038-1377', '1985-07-29', 'false'),
	('Rev. Aron Ruecker Johns', '+34 (130) 550-1753', '1981-04-24', 'false'),
	('Brant Harvey Hessel', '+52 1-668-118-2256 x3697', '1998-08-08', 'true'),
	('Mr. Delmer Hayes OHara', '+61-8 987.676.6843', '1978-07-13', 'true'),
	('Andrea Ernser Bartoletti', '+1-784 (216) 155-0761 x19493', '1960-12-28', 'false'),
	('Rep. Jonathan Thiel Blick', '+974 (864) 019-7923', '1988-12-03', 'false'),
	('Andreas Gusikowski Jacobson DC', '+420 151.381.3348', '1991-04-02', 'false'),
	('Crysta Stark Bechtelar', '+886 617-681-0095 x53821', '1994-06-29', 'true'),
	('Kathrin Leffler McGlynn', '+41 (935) 052-8115 x1495', '1990-08-07', 'true'),
	('Solomon VonRueden Spencer', '+244 286.171.4334', '1966-08-22', 'true'),
	('Onie McClure Stracke', '+213 550-861-3626 x0002', '1973-03-16', 'true'),
	('Tenisha Lehner Jacobi', '+298 1-441-702-5578', '1992-05-24', 'true'),
	('Amb. Delmer Hauck Hahn', '+974 689-418-9189 x39958', '2004-05-27', 'false'),
	('Emelia Kulas Cronin', '+95 710.131.5151', '1978-02-24', 'false'),
	('Tempie Medhurst Boehm', '+976 754-042-4864 x591', '1961-01-04', 'true'),
	('Eric Romaguera Will', '+503 548.489.6806 x4979', '1981-07-17', 'false'),
	('Cleo Bednar Kunze', '+248 (587) 765-7193 x027', '1959-12-15', 'false'),
	('Mr. Sheilah Funk Gorczany', '+855 (631) 547-6445 x91671', '1973-05-10', 'false'),
	('Karey Parisian Gulgowski', '+423 (777) 310-1198 x0938', '1973-11-03', 'false'),
	('Vicenta Kunde Kerluke', '+32 555.722.7387 x83749', '1978-11-22', 'true'),
	('Wilma Altenwerth Schamberger', '+505 980.673.8950 x7221', '1974-08-05', 'true'),
	('Prof. Kasey Pollich Grant', '+680 357-135-0482 x64471', '1974-09-24', 'false'),
	('Sommer Runte Will', '+1-340 376.049.9683 x5707', '1979-11-18', 'false'),
	('Hai Hodkiewicz Donnelly', '+265 1-212-974-9366 x2501', '1970-02-23', 'true'),
	('Stanford Trantow Ratke IV', '+1-264 496.114.7357 x3247', '1974-07-12', 'true'),
	('Cynthia Bahringer Schoen', '+269 1-701-193-4764 x187', '2003-12-16', 'false'),
	('Delbert Hilll Herman', '+966 953-867-3779', '1965-05-07', 'true'),
	('Ross Wisoky Brakus Sr.', '+421 322.121.3014 x1792', '1961-12-23', 'false'),
	('Adalberto MacGyver Strosin', '+594 371.271.6075', '2002-06-13', 'false'),
	('Warren Hammes Beatty MD', '+681 972.216.6622 x88152', '1971-09-10', 'true'),
	('Kisha Miller Johns PhD', '+370 434.477.1719 x21613', '1979-09-07', 'true'),
	('The Hon. Hyman Reichel Lynch', '+240 (832) 882-3408', '1962-08-03', 'false'),
	('Olevia Mosciski Runolfsdottir', '+996 981.780.2421 x9820', '1980-04-12', 'true'),
	('Rep. Frances Sanford Schuppe', '+972 770.400.4880', '1989-05-30', 'true'),
	('Maricruz Flatley Schimmel', '+82 1-168-220-4956 x6771', '1991-03-15', 'true'),
	('Lindsay Waelchi Bahringer', '+238 921.344.0507', '1963-01-23', 'false'),
	('Bryanna Prosacco Smith', '+86 1-529-962-4500 x72060', '1964-01-09', 'false'),
	('Tania Turcotte Witting', '+1-868 (374) 921-0207', '1961-06-10', 'false'),
	('Annetta Kunze Cummerata', '+240 122.573.9579 x980', '1982-08-29', 'true'),
	('Fred Wiegand Dickens', '+223 616.556.4034 x898', '1993-01-27', 'true'),
	('Nu Koepp OHara', '+41 960.658.7512', '1996-08-27', 'true'),
	('Lucie Walter Fisher', '+228 (331) 592-2479 x008', '2000-04-01', 'true'),
	('Rocky Ernser Maggio', '+27 1-259-801-3994 x7947', '1968-07-08', 'false'),
	('Carley Nitzsche Howell', '+670 1-764-274-9759 x2882', '1964-06-16', 'false'),
	('Mason Johnson Bernhard', '+507 178-563-5717 x56815', '1980-05-19', 'false'),
	('Walker Padberg Hahn', '+49 939-210-1142 x93115', '1976-08-26', 'false'),
	('Mrs. Alejandra Wuckert Skiles', '+687 668.406.7126 x53466', '1986-12-29', 'true'),
	('Vernon Bayer Douglas', '+63 166-979-7037', '1963-01-14', 'false'),
	('Issac Mann Zemlak', '+240 827.590.0663 x84291', '1989-02-17', 'true'),
	('Chadwick Kautzer Gusikowski', '+371 193.130.0425 x33506', '1966-01-11', 'false'),
	('Debi Mueller Thompson I', '+509 (277) 991-3178 x142', '1973-10-29', 'true'),
	('Lu Zulauf OHara', '+258 (282) 064-4045 x29697', '1959-10-11', 'false'),
	('Floria Howe Mitchell DVM', '+240 624.058.0014 x36935', '1966-08-16', 'false'),
	('Lilliam Gutmann Schultz I', '+596 (315) 220-2027 x4840', '1987-05-11', 'true'),
	('Sen. Noel Parisian Wiza', '+352 445.243.1224', '1987-11-15', 'true'),
	('Gema Wiegand Rodriguez DC', '+218 1-401-403-9837 x882', '1970-07-24', 'false'),
	('Roselyn Christiansen Littel', '+385 (378) 090-0576 x501', '2001-09-13', 'false'),
	('Fr. Verona Hackett Ullrich', '+290 222-580-4388 x2629', '1965-08-02', 'false'),
	('Doria Bednar Powlowski Sr.', '+1-939 1-466-239-4632', '1989-07-25', 'true'),
	('Danae Hills Kihn', '+809 348-837-7499', '1960-05-02', 'true'),
	('Dr. Kenyatta Walter Mertz', '+33 774.626.4649', '2002-10-23', 'true'),
	('Samella MacGyver Armstrong', '+386 1-541-261-2479 x66491', '1971-04-12', 'false'),
	('Delinda Keeling Shields', '+297 (958) 475-8697 x91598', '1999-03-08', 'false'),
	('Carry Hackett Cronin', '+218 (398) 971-0805', '1995-02-19', 'true'),
	('Annamaria Bauch Gutmann VM', '+677 534.715.1988', '1970-03-28', 'false'),
	('Letha Hilll Von', '+850 908-202-5805', '1994-09-01', 'true'),
	('Leanne Schneider Goodwin', '+47 (488) 712-2242 x4672', '1996-12-06', 'false'),
	('Maryjo Romaguera Terry', '+993 (114) 977-2618 x35832', '1982-05-19', 'false'),
	('Kevin Hamill Watsica', '+855 1-916-637-8365', '1969-10-18', 'false'),
	('Johnetta Rogahn McClure', '+44 (532) 506-6166 x01320', '1962-09-21', 'false'),
	('Bradley Pollich Leffler', '+973 (126) 731-3277', '1974-01-30', 'true'),
	('Shara Doyle Paucek DDS', '+39 1-698-330-0088 x6966', '1963-03-08', 'false'),
	('Fredrick Turcotte Spinka', '+81 205.548.7559 x135', '1986-05-17', 'true');
INSERT INTO flights (price, meal_included, flight_duration,  departure_time, aircompany_id,  departure_airport_id, arrival_airport_id) VALUES
	('4171', 'false', '11', '2023-04-18 16:25:27 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('809', 'false', '9', '2023-04-18 15:04:20 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2749', 'true', '4', '2023-04-17 10:05:23 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1830', 'true', '11', '2023-04-19 01:06:27 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('333', 'false', '16', '2023-04-21 13:19:36 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4104', 'true', '19', '2023-04-20 12:25:34 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1132', 'true', '5', '2023-04-23 19:11:24 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('704', 'true', '9', '2023-04-21 00:36:24 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4603', 'false', '7', '2023-04-21 19:40:39 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2925', 'false', '10', '2023-04-20 10:35:02 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('977', 'false', '11', '2023-04-23 21:05:00 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3932', 'true', '19', '2023-04-18 05:44:23 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('472', 'false', '12', '2023-04-19 14:17:30 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1752', 'true', '12', '2023-04-22 04:14:20 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3518', 'true', '2', '2023-04-23 07:42:42 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3888', 'false', '7', '2023-04-21 18:50:18 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2526', 'false', '3', '2023-04-20 03:37:57 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3171', 'true', '2', '2023-04-17 00:46:29 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1851', 'true', '16', '2023-04-21 22:09:42 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4565', 'true', '7', '2023-04-19 10:44:40 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4702', 'true', '17', '2023-04-17 04:03:24 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4426', 'false', '1', '2023-04-17 17:34:00 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4817', 'true', '17', '2023-04-17 20:32:15 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('813', 'false', '2', '2023-04-20 06:20:55 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1225', 'true', '6', '2023-04-19 04:05:09 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('128', 'false', '8', '2023-04-18 10:51:53 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4237', 'false', '4', '2023-04-22 01:44:07 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1273', 'false', '11', '2023-04-22 05:34:22 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('161', 'true', '6', '2023-04-19 16:54:40 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3369', 'false', '7', '2023-04-23 02:20:33 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2874', 'false', '11', '2023-04-23 14:36:33 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('91', 'true', '2', '2023-04-18 20:13:34 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3458', 'true', '1', '2023-04-22 03:37:20 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3570', 'false', '13', '2023-04-22 13:35:27 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3330', 'false', '18', '2023-04-21 19:44:21 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('513', 'true', '13', '2023-04-21 07:34:21 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4396', 'true', '5', '2023-04-23 19:38:31 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3925', 'false', '4', '2023-04-17 19:59:04 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1120', 'true', '7', '2023-04-23 17:20:41 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3364', 'true', '7', '2023-04-18 14:36:54 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4710', 'true', '16', '2023-04-19 00:59:50 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3873', 'true', '16', '2023-04-18 06:28:12 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4369', 'true', '20', '2023-04-18 12:26:14 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3838', 'false', '18', '2023-04-18 06:56:22 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1956', 'true', '6', '2023-04-20 00:31:33 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('973', 'false', '18', '2023-04-18 08:54:00 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('519', 'false', '7', '2023-04-19 16:14:14 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4881', 'false', '13', '2023-04-19 01:24:04 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3777', 'true', '2', '2023-04-17 19:11:21 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('875', 'false', '1', '2023-04-23 20:56:14 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3261', 'true', '16', '2023-04-21 07:10:17 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2780', 'true', '10', '2023-04-19 02:34:39 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3936', 'true', '15', '2023-04-18 11:28:31 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1644', 'false', '12', '2023-04-19 19:22:50 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('332', 'false', '12', '2023-04-21 23:55:19 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3691', 'true', '1', '2023-04-20 19:10:36 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1044', 'false', '16', '2023-04-17 08:41:48 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2198', 'true', '4', '2023-04-19 15:14:00 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3265', 'false', '7', '2023-04-17 00:57:16 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('739', 'false', '14', '2023-04-21 06:07:43 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3674', 'true', '20', '2023-04-21 23:54:13 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2352', 'false', '4', '2023-04-21 18:17:07 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3835', 'true', '16', '2023-04-23 12:39:25 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4422', 'true', '15', '2023-04-22 14:55:37 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2485', 'false', '8', '2023-04-20 17:43:52 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3207', 'true', '12', '2023-04-19 21:25:30 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4333', 'false', '8', '2023-04-19 12:04:31 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1728', 'false', '17', '2023-04-23 10:26:43 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2765', 'false', '13', '2023-04-21 08:22:55 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('938', 'false', '4', '2023-04-18 16:07:22 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('905', 'true', '19', '2023-04-21 18:04:07 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('400', 'true', '17', '2023-04-19 07:42:04 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1675', 'false', '1', '2023-04-22 02:02:35 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4668', 'true', '15', '2023-04-17 04:45:54 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('423', 'true', '1', '2023-04-17 19:53:18 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4412', 'true', '12', '2023-04-21 20:35:37 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('564', 'true', '6', '2023-04-17 11:16:55 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4527', 'false', '11', '2023-04-21 03:54:28 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2507', 'false', '19', '2023-04-20 05:29:35 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('729', 'false', '2', '2023-04-22 17:01:58 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1445', 'false', '7', '2023-04-17 23:20:16 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1946', 'true', '2', '2023-04-22 11:41:03 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2455', 'false', '6', '2023-04-21 07:04:51 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('664', 'true', '12', '2023-04-18 21:00:50 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('158', 'true', '10', '2023-04-20 23:40:27 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2004', 'true', '1', '2023-04-21 06:17:16 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('101', 'false', '14', '2023-04-22 14:16:39 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1066', 'true', '2', '2023-04-18 17:44:41 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1229', 'false', '2', '2023-04-22 19:13:28 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2321', 'true', '19', '2023-04-22 14:42:37 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('799', 'false', '20', '2023-04-21 21:13:01 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3914', 'false', '10', '2023-04-18 06:38:31 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2072', 'true', '19', '2023-04-17 19:09:01 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('799', 'true', '9', '2023-04-21 22:46:19 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2511', 'false', '16', '2023-04-22 16:12:09 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3792', 'false', '13', '2023-04-17 23:31:31 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1753', 'false', '16', '2023-04-18 09:37:40 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1990', 'true', '8', '2023-04-23 00:40:10 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('972', 'true', '20', '2023-04-20 14:05:11 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('358', 'true', '11', '2023-04-22 10:04:51 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2987', 'false', '11', '2023-04-22 23:51:56 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1));
INSERT INTO trips (departure_flight_id, hotel_id, meal) VALUES
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' );
UPDATE trips SET arrival_flight_id = (SELECT id from flights where flights.departure_time > (SELECT departure_time FROM flights where flights.id = trips.departure_flight_id) ORDER BY random() LIMIT 1),
        departure_date = (SELECT departure_time from flights where flights.id = trips.departure_flight_id );
UPDATE trips SET arrival_date = (SELECT departure_time from flights where flights.id = trips.arrival_flight_id );
INSERT INTO workers (full_name, phone, birthday_date, salary) VALUES
	('Roger Hackett Emard', '+66 889.427.2949 x1286', '1987-06-07', 2365),
	('Tommye Wiza Cummerata', '+971 (742) 351-0332 x28167', '1979-05-11', 1838),
	('Buck Boyer Moen', '+421 (467) 317-3616 x26780', '1978-02-10', 1915),
	('Elli Dietrich Ankunding', '+1-787 574-169-5850 x866', '2004-08-20', 3272),
	('Christiana Rau Medhurst', '+598 610-669-6763 x4225', '1981-06-30', 3179),
	('Loan OConnell Lebsack', '+508 468-438-9585 x4823', '1967-10-23', 2544),
	('Dr. Dwana Yost Osinski', '+1-784 1-610-627-2765 x3111', '1970-03-05', 1929),
	('Ellena Nicolas Rice', '+767 (334) 809-9485 x3396', '1988-06-03', 783),
	('Delinda Mraz DAmore', '+216 891.793.6045 x57135', '2000-11-05', 3186),
	('Msgr. Hayden Goyette Gleason', '+376 918.482.7245 x47342', '1980-03-03', 4754),
	('Mallory Jenkins Kshlerin Ret.', '+386 874.915.5854 x18926', '1980-07-12', 3478),
	('Sen. Marguerite Weissnat Lockman', '+33 1-229-883-2155', '1997-07-14', 3011),
	('Tony Lindgren Powlowski', '+674 1-597-249-9657', '2000-12-24', 2207),
	('Dorcas Lowe Kirlin', '+7 (323) 524-7458 x2403', '1958-12-09', 2254),
	('Shirl Glover Wilderman', '+599 960-750-4015', '1989-01-23', 626),
	('Mohammad Lubowitz Beier', '+252 944-155-4112 x89802', '1998-04-30', 1594),
	('Miss Santos Grimes Little', '+253 (719) 857-5160', '1985-03-22', 4090),
	('Danae OKon Pacocha Ret.', '+680 736-957-8143 x63839', '1992-02-17', 1606),
	('Lera Stark Parker', '+503 (523) 623-3986', '1976-09-11', 3647),
	('Kasey VonRueden Thiel', '+504 (104) 248-0717', '1966-03-07', 2982),
	('Suzy Parisian Hamill V', '+850 (540) 932-7363 x756', '1988-08-24', 4438),
	('Debby Collier Bechtelar', '+58 (507) 106-6885 x22751', '1985-04-26', 227),
	('Keena Rodriguez OConner', '+596 923-369-9788 x65366', '1983-07-31', 2035),
	('Shad Ullrich Sanford', '+252 (417) 986-0677 x60218', '1965-06-27', 3345),
	('Maryetta Rau Ortiz II', '+853 639.970.5034 x370', '1959-07-05', 3254),
	('Maryam Herzog Lynch', '+353 (804) 653-4903 x642', '2003-12-05', 3422),
	('Elisa Berge Walter Esq.', '+597 1-456-759-0121 x15883', '1978-04-15', 2661),
	('Chuck Jones Grady DO', '+1-473 147-714-3496 x13816', '1971-06-13', 1670),
	('Prof. Ingrid Schroeder Koepp', '+222 818.912.0587 x468', '1958-04-20', 1009),
	('Rev. Eugenio Kutch Medhurst', '+1-784 1-722-409-1474 x6614', '1992-12-25', 3610),
	('Rev. Elisha Zieme Walker', '+30 607-862-6049 x80739', '1981-11-10', 1496),
	('Tegan Maggio Smitham', '+963 (493) 200-7604 x24609', '1996-09-03', 2428),
	('Mica Ferry Hayes', '+371 532.590.2601 x5331', '1983-06-09', 4069),
	('Alberto Von Leuschke', '+595 (318) 709-2848', '1964-07-13', 4581),
	('Efren Leuschke McDermott', '+66 1-272-963-2901 x9910', '2004-05-24', 2940),
	('Jim Parisian Zemlak DDS', '+91 (323) 319-8411 x9116', '1972-08-21', 2983),
	('Sal Koelpin Powlowski', '+974 528.042.8330', '1961-03-06', 1470),
	('Norberto OConner Rempel', '+996 365.529.2941 x172', '1990-03-30', 3097),
	('Valentin Pacocha Goodwin', '+1-868 815.320.3218 x455', '1980-11-28', 1988),
	('Carmelia Kohler Pfeffer Jr.', '+51 269.656.2821 x2068', '1970-06-18', 2278),
	('Fr. Donita Lesch Bernhard', '+972 753-510-6084 x50892', '1976-02-25', 4911),
	('Walter Cronin Prosacco MD', '+1-246 (980) 422-4248 x139', '1982-04-24', 2242),
	('Stacy Emmerich Rutherford', '+855 697.153.8398', '1965-12-28', 1225),
	('Lino Hudson Zemlak', '+679 623.687.4268 x21328', '1980-02-15', 4971),
	('Randolph Crooks Wisozk', '+46 1-714-592-9483', '1963-06-09', 4416),
	('Rep. Kerry Nikolaus White', '+221 724-162-0196 x81014', '1962-05-24', 3723),
	('Lakenya Goodwin Koepp', '+385 857-014-6550 x2690', '1962-06-10', 1063),
	('Emory Reinger Bashirian', '+1-473 935.147.4929', '1981-03-21', 2519),
	('Antone Rempel Douglas VM', '+502 644.767.8337 x1267', '1999-06-29', 2261),
	('Emmitt Raynor Ratke', '+421 (177) 588-6254 x5001', '1988-06-28', 1047),
	('Keith Bernier Lesch', '+380 1-154-538-1519 x6957', '1989-04-08', 70),
	('Burl Rice Kautzer', '+255 885.887.1741', '1986-04-15', 2716),
	('Mario Lowe Frami', '+92 (250) 001-7218', '2001-05-05', 4599),
	('Geoffrey Greenfelder Funk', '+223 1-464-078-6953', '1976-12-31', 3590),
	('Tory Borer Bogan', '+387 245.667.8998 x1941', '1968-12-02', 1879),
	('Roderick Wiza Schuppe', '+262 1-127-043-6978 x7699', '1994-12-19', 2016),
	('Mohammed Auer Waelchi', '+265 1-534-727-0711 x972', '2001-12-09', 980),
	('Msgr. Maricela Skiles McClure', '+381 880-236-5442 x958', '1982-12-29', 4393),
	('Shanda Yundt Halvorson', '+1-671 (341) 532-9567 x314', '1969-11-21', 2129),
	('Sen. Stanford Batz Casper', '+354 176.440.5663 x43106', '1995-10-15', 4957),
	('Debroah Abshire Morar', '+677 1-685-560-8864', '1980-03-30', 2807),
	('Jessenia Veum Johnston', '+261 (283) 550-2369 x22190', '1995-11-10', 1822),
	('Janna Bauch Paucek Sr.', '+232 1-202-918-7080 x66546', '1974-09-05', 573),
	('Miss Dorothea Wiza Jacobson', '+993 (227) 933-6247 x019', '1978-12-16', 3864),
	('Oswaldo Volkman Olson MD', '+7-6 1-188-045-3828 x50274', '1987-03-20', 1143),
	('Carissa Nader Hoeger', '+372 1-595-756-1302 x064', '1976-01-12', 150),
	('Thersa Pagac Beier', '+299 1-292-515-6847 x3029', '1959-10-12', 1491),
	('Dewitt Beer Green', '+213 1-786-235-5786 x446', '1999-09-28', 3296),
	('Lesley Turner Reichert', '+234 381.804.9367 x05355', '1971-10-27', 3515),
	('Prof. Nick Crooks Schamberger', '+247 548-960-9698 x51023', '1968-10-29', 2141),
	('Season Parisian Friesen', '+44 100-936-9796 x5145', '1962-10-30', 1310),
	('Tennille Abshire Christiansen', '+1-671 885-026-8214', '1968-08-14', 1666),
	('Dwain Goldner Yundt', '+809 432.446.4143 x214', '2000-03-15', 237),
	('Ellis Volkman Langosh', '+594 1-310-046-3925 x58180', '1985-03-12', 976),
	('Bree Bailey Franecki', '+233 1-142-173-8622 x87595', '1968-01-11', 4355),
	('Pres. Javier Olson Kling', '+235 669-487-1179', '1961-01-06', 178),
	('Rep. Denver Moen Gleason', '+48 (936) 036-4891 x805', '1997-03-17', 2413),
	('Colin Gusikowski Anderson', '+86 237.588.8942', '1958-08-30', 1183),
	('Thu Luettgen Mayer DVM', '+993 269-510-6210 x33503', '1963-12-23', 1812),
	('Jay Grant Hagenes', '+355 442.641.8561 x02506', '1975-06-05', 2493),
	('Fawn Okuneva Bergnaum', '+260 1-122-451-4241 x3825', '1976-06-27', 3815),
	('Ramiro Jast Marks', '+258 (257) 898-9987 x525', '1978-08-24', 3942),
	('Vincent Bins Beer', '+964 977-312-4692 x26189', '1959-06-25', 1536),
	('Marlena Prohaska Yundt', '+370 1-682-339-9502 x726', '1991-04-07', 1809),
	('Bob Hills Walsh', '+678 132-167-2035', '2002-06-05', 4234),
	('Jordon DuBuque Kemmer LLD', '+509 (475) 186-9881 x8335', '1982-09-04', 4930),
	('Faye Thompson Emmerich', '+228 (493) 947-2839 x9813', '1987-06-14', 1214),
	('Dorie Lebsack Gleichner', '+31 (970) 507-2394 x4264', '1964-06-30', 3322),
	('Jospeh Kuhic Orn', '+228 342.682.6460 x6417', '1972-02-27', 2444),
	('Shelby Tillman Cronin', '+53 633-291-5895 x5612', '1981-01-22', 695),
	('Madonna Corkery Hane', '+421 216-858-0676 x667', '1994-05-08', 1350),
	('Val Gutkowski Hodkiewicz', '+212 1-102-594-1536 x5810', '1999-07-17', 468),
	('Lashawna Koch Baumbach', '+252 385-829-4643', '1967-06-30', 2369),
	('Wilmer Willms Wuckert', '+1-939 (935) 962-8667', '1992-02-22', 4686),
	('Janella Herman Emmerich', '+672 150.448.0455 x208', '1988-09-22', 2588),
	('Octavio Renner Wuckert', '+960 1-257-485-1751 x695', '1979-05-09', 4363),
	('Chang Marquardt Cole PhD', '+256 174-939-7862 x892', '1992-04-20', 596),
	('Blanche Casper Von', '+968 568-260-0439', '1997-03-23', 2137),
	('Joana Murazik Schinner', '+687 445-908-4907 x9689', '1965-06-22', 3679),
	('Diann Padberg Crooks LLD', '+353 520.692.0975 x5705', '1981-03-15', 2315),
	('Sen. Louise McLaughlin Feest', '+242 691.540.7720 x374', '1993-04-24', 4521);
