INSERT INTO aircompanies (name) VALUES
	('Lubowitz LLC'),
	('Homenick, Rohan and Parker'),
	('Tillman, Roob and Murazik'),
	('Daniel Inc'),
	('Gislason LLC'),
	('Wintheiser, Turcotte and Tillman'),
	('Wiza-Gutkowski'),
	('Schmeler Group'),
	('Murazik-OKeefe'),
	('Dooley, Smitham and Roob'),
	('Kerluke, Quitzon and Keebler'),
	('Spinka Inc'),
	('Spencer, Torphy and Kris'),
	('Kulas-Marquardt'),
	('Becker, Koss and Monahan'),
	('Fahey, Langosh and Hamill'),
	('VonRueden Group'),
	('Aufderhar-Reichel'),
	('Sanford, Deckow and Hilpert'),
	('Labadie, Keebler and Collins'),
	('Kautzer-Lehner'),
	('Wilderman-Bergnaum'),
	('Wuckert Group'),
	('Raynor-Block'),
	('Hilll-McClure'),
	('McKenzie-Langworth'),
	('Gusikowski, Raynor and Kirlin'),
	('Stanton-Kovacek'),
	('Denesik-Collins'),
	('Aufderhar-Lockman'),
	('Kuhlman Inc'),
	('Hahn-Kshlerin'),
	('Trantow-Heller'),
	('Fritsch LLC'),
	('Sporer, Mills and Goldner'),
	('Pouros-Krajcik'),
	('Dach, Wunsch and Daugherty'),
	('Pagac, Reynolds and Klein'),
	('Schuppe Group'),
	('Ferry LLC'),
	('Kuhlman LLC'),
	('Leuschke, Blick and Reinger'),
	('Rogahn Group'),
	('Borer LLC'),
	('Bogan and Sons'),
	('Hermann-Grimes'),
	('Marvin-Bernier'),
	('Hauck LLC'),
	('Orn-Haag'),
	('Feest-Wuckert'),
	('Reilly-Brown'),
	('Mitchell, Bernhard and Altenwerth'),
	('Raynor-Pagac'),
	('Kirlin, Wiegand and Schulist'),
	('Douglas-DuBuque'),
	('Doyle, Parker and Watsica'),
	('Murphy, Rohan and Harris'),
	('Waelchi and Sons'),
	('Johns-Ebert'),
	('Homenick, Terry and Luettgen'),
	('Hermiston Group'),
	('Hirthe, Spinka and Shanahan'),
	('Torphy and Sons'),
	('Ryan and Sons'),
	('Huel, Blanda and Koelpin'),
	('Rice, Harris and Olson'),
	('Hoppe, Morar and Ruecker'),
	('Walsh LLC'),
	('Jast, Reinger and Medhurst'),
	('Reynolds, Schmitt and Kemmer'),
	('Olson, Stroman and Witting'),
	('Murphy Inc'),
	('Torphy-Wolf'),
	('Nader-Skiles'),
	('Reichert-Lebsack'),
	('Ullrich, Homenick and Braun'),
	('Cremin and Sons'),
	('Emard, Boehm and Green'),
	('Wisoky-Kling'),
	('Jerde, Klocko and Crist'),
	('Renner, Bauch and Legros'),
	('Koss Inc'),
	('Swaniawski-Wyman'),
	('Lakin Inc'),
	('Macejkovic, Runolfsdottir and Bahringer'),
	('Cronin Group'),
	('Mayer-Heathcote'),
	('Hayes Group'),
	('Torphy-Anderson'),
	('Yundt-McCullough'),
	('Cronin-Oberbrunner'),
	('Watsica, Kshlerin and Barrows'),
	('McDermott, Cormier and Jaskolski'),
	('Howell, Rath and Pfannerstill'),
	('Kling-Crist'),
	('Mante-Keebler'),
	('Kshlerin-Dare'),
	('Okuneva and Sons'),
	('Stanton, Schuster and Oberbrunner'),
	('Bauch, Jacobi and Aufderhar'),
	('Wisozk, Hackett and DuBuque');
INSERT INTO countries (name) VALUES
	('Australia'),
	('Tuvalu'),
	('Guam'),
	('Western Sahara'),
	('Azerbaijan'),
	('Brunei Darussalam'),
	('Myanmar'),
	('Kenya'),
	('Martinique'),
	('Pitcairn Islands'),
	('Myanmar'),
	('Luxembourg'),
	('United States Minor Outlying Islands'),
	('Hong Kong'),
	('Comoros'),
	('Uruguay'),
	('Tonga'),
	('Albania'),
	('Tokelau'),
	('Malawi'),
	('Portugal'),
	('Azerbaijan'),
	('Liechtenstein'),
	('Namibia'),
	('Bermuda'),
	('Western Sahara'),
	('Cameroon'),
	('Saint Barthelemy'),
	('Guinea'),
	('Armenia'),
	('Vanuatu'),
	('Reunion'),
	('Jersey'),
	('Nigeria'),
	('Papua New Guinea'),
	('Solomon Islands'),
	('Slovenia'),
	('Nicaragua'),
	('Papua New Guinea'),
	('Malaysia'),
	('Canada'),
	('Slovenia'),
	('Mali'),
	('New Caledonia'),
	('Sierra Leone'),
	('Zimbabwe'),
	('Dominica'),
	('British Indian Ocean Territory (Chagos Archipelago)'),
	('Yemen'),
	('Cayman Islands'),
	('Georgia'),
	('Tanzania'),
	('Kyrgyz Republic'),
	('Equatorial Guinea'),
	('Haiti'),
	('Saint Martin'),
	('Panama'),
	('Benin'),
	('China'),
	('Greece'),
	('Cameroon'),
	('Cambodia'),
	('Montenegro'),
	('Brunei Darussalam'),
	('Azerbaijan'),
	('Turks and Caicos Islands'),
	('Norfolk Island'),
	('Norway'),
	('Tanzania'),
	('Falkland Islands (Malvinas)'),
	('Kiribati'),
	('Saint Pierre and Miquelon'),
	('Grenada'),
	('Grenada'),
	('Argentina'),
	('Iceland'),
	('Costa Rica'),
	('Namibia'),
	('United States Minor Outlying Islands'),
	('Iceland'),
	('Mauritius'),
	('Holy See (Vatican City State)'),
	('Nicaragua'),
	('Denmark'),
	('New Caledonia'),
	('Uzbekistan'),
	('Malawi'),
	('Gabon'),
	('Comoros'),
	('French Southern Territories'),
	('Saint Vincent and the Grenadines'),
	('Sudan'),
	('Jordan'),
	('Djibouti'),
	('United States Minor Outlying Islands'),
	('Solomon Islands'),
	('Sao Tome and Principe'),
	('Senegal'),
	('Argentina'),
	('Azerbaijan'),
	('Hilpert Inc');
INSERT INTO cities (name, country_id) VALUES
	('Lake Clint', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Langworthmouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Murrayside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Jakechester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Jcton', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Mertzbury', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Miltonton', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Shellifurt', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Astridstad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Schroederhaven', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Ambrosemouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Oraleestad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Carminabury', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Ettiefort', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Huelsview', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Douglassstad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Vinnieland', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Brakusfurt', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Drewchester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Botsfordhaven', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Sylvester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lyndseyville', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Nataliafort', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Jamie', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Vonton', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Stanley', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Nickolasburgh', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Hilpertland', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Allenmouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Friesenhaven', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Koreyside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('OHarahaven', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Maye', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Wilfred', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Louis', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Naderbury', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Feeneymouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Lacy', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Carrishire', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Simonmouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Sarinamouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Shadmouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Kristopherhaven', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Cordeliaside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Jessemouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Kurt', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Batzchester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Dean', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Maisiebury', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Jaskolskiborough', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Hansenport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Ricardo', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Jerdehaven', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Dan', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Valentine', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Tuanberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Hoseatown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Daniahaven', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Creminburgh', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Rennerberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Dion', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Considinefort', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Mike', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Bernardo', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Ricechester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Thadborough', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Teodoroview', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Moriahberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Ellsworth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Elias', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Loisemouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Tish', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('DuBuquetown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Queenieburgh', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Estherberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Luthertown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Yishire', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Freddaborough', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Jaymefurt', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Olinside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Satterfieldhaven', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('OConnellchester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Wallyshire', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Donland', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Mickiland', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Xochitl', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Jacki', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Janside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Labadieberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Valentina', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Tomikohaven', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Meistad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Maudieborough', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Lowellbury', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Borerberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Valorie', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Dino', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Marge', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Seth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Georgannburgh', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Gleichner LLC', (SELECT id FROM countries ORDER BY random() LIMIT 1));
INSERT INTO airports (name, city_id) VALUES
	('Orlando International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Newark Liberty International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Minneapolis Saint Paul International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('LaGuardia Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Newark Liberty International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Daniel K. Inouye International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Denver International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Charlotte Douglas International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('George Bush Intercontinental Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Harry Reid International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Minneapolis Saint Paul International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Salt Lake City International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Minneapolis Saint Paul International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dulles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('John F. Kennedy International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Portland International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('John F. Kennedy International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ronald Reagan Washington National Airport**', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Portland International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hartsfield Jackson Atlanta International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Midway International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Minneapolis Saint Paul International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Salt Lake City International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Seattle Tacoma International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Francisco International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Francisco International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Philadelphia International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Detroit Metropolitan Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dulles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Harry Reid International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Midway International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Salt Lake City International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dulles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Minneapolis Saint Paul International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('OHare International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Francisco International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Denver International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tampa International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Minneapolis Saint Paul International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tampa International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Phoenix Sky Harbor International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Harry Reid International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('LaGuardia Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Newark Liberty International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Salt Lake City International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Detroit Metropolitan Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Charlotte Douglas International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Portland International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('John F. Kennedy International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Daniel K. Inouye International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tampa International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Diego International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hartsfield Jackson Atlanta International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hartsfield Jackson Atlanta International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Seattle Tacoma International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Midway International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Francisco International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Logan International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Denver International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Logan International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Midway International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Newark Liberty International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('OHare International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Diego International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Denver International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hartsfield Jackson Atlanta International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('LaGuardia Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Orlando International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Francisco International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Philadelphia International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Detroit Metropolitan Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Detroit Metropolitan Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('LaGuardia Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Harry Reid International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Philadelphia International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Daniel K. Inouye International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1));
INSERT INTO hotels (name, has_pool, number_of_stars, cleaning_included, price_for_a_person, city_id) VALUES
	('Eleanora Thompson McKenzie VM', 'false', 3, 'false', 56, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Demetria Haley Glover', 'false', 2, 'false', 47, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tony Hills Armstrong', 'true', 3, 'false', 9, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Sen. Diego Moen Watsica', 'false', 5, 'true', 64, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Clemente Leuschke Murazik Esq.', 'false', 1, 'false', 27, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Lindsy Gusikowski Ward', 'false', 2, 'false', 98, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Krysta Dickinson Wolf I', 'true', 2, 'true', 49, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dustin Schumm Fay', 'false', 5, 'false', 18, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Reynaldo Reilly Hudson', 'true', 4, 'true', 193, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Jimmie Simonis Cummerata', 'false', 1, 'false', 13, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Kathryne Bernhard Green', 'true', 2, 'true', 14, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Darrick Ankunding Hahn', 'false', 3, 'true', 55, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Debroah Abshire Kozey', 'true', 4, 'false', 120, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Melba Cartwright Armstrong', 'true', 2, 'true', 6, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Melony Maggio Boehm I', 'false', 4, 'true', 67, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Sen. Angel Gerhold Kerluke', 'false', 2, 'false', 45, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Jonna Heathcote Volkman VM', 'true', 1, 'true', 4, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Karl Treutel DuBuque', 'true', 2, 'false', 59, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Matt Grimes Stamm', 'true', 2, 'false', 34, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Quiana Block Roberts', 'true', 2, 'false', 32, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Gayle Lehner Braun', 'false', 3, 'false', 139, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Cara Lemke Reinger', 'false', 1, 'false', 13, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Quintin Cartwright Prohaska', 'true', 4, 'true', 23, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dusti Christiansen Abernathy', 'true', 1, 'false', 18, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Danny Pacocha Dach', 'false', 2, 'true', 51, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Loren Wisoky Koelpin', 'false', 3, 'true', 92, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Delphia Rohan Daugherty DVM', 'false', 2, 'false', 33, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Sen. Adah Mraz Bode', 'false', 4, 'true', 176, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mohamed Gerlach Schroeder', 'false', 2, 'false', 63, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Arianne Cruickshank Kris Jr.', 'true', 2, 'false', 48, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Palmer Jacobs Mueller V', 'true', 2, 'true', 4, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Oscar Ankunding Renner Esq.', 'false', 1, 'true', 48, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Andy Hermiston Waters', 'false', 2, 'true', 40, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Kisha Tillman Haley', 'false', 3, 'true', 88, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Aleen Bosco Walter', 'true', 5, 'false', 73, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fletcher Vandervort Kilback', 'false', 4, 'false', 139, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Msgr. Jame Ledner Reinger', 'false', 5, 'true', 62, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Sen. Elliot Konopelski Kerluke', 'true', 5, 'true', 103, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Sueann Prosacco Fahey', 'false', 2, 'false', 39, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Barry Jakubowski Hyatt', 'false', 3, 'true', 48, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Truman Dooley Kshlerin III', 'false', 4, 'false', 183, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Bobbie Walter Fadel', 'false', 5, 'false', 182, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Josef Cassin Dach DO', 'true', 1, 'true', 39, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Sung Halvorson Prohaska', 'false', 2, 'true', 36, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Yuk Corwin Paucek DDS', 'true', 5, 'false', 24, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Marya Grimes Stokes', 'false', 2, 'true', 50, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Cruz Breitenberg Heller', 'false', 1, 'false', 25, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Reed Stiedemann Bashirian', 'true', 3, 'true', 0, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Arlie Bednar Watsica', 'false', 4, 'true', 182, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Rob Watsica Huel', 'true', 5, 'false', 144, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Bong Kautzer Keeling', 'false', 3, 'false', 24, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Valentin Collier Rath MD', 'false', 5, 'false', 98, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ashley Walter Weber', 'false', 1, 'false', 24, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Denis Koss Price', 'true', 3, 'false', 131, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Pres. Lai Lockman Towne', 'true', 5, 'true', 138, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('The Hon. Terrell Gleichner Ryan', 'true', 2, 'false', 12, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Gail Kuhlman Sipes', 'true', 1, 'true', 16, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Monte Gutkowski Kohler', 'false', 5, 'false', 139, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ashli Schamberger Konopelski', 'true', 2, 'false', 78, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Bobette Krajcik Schinner', 'false', 3, 'false', 20, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Clarence Bashirian Klocko DVM', 'false', 3, 'false', 15, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Augustus Gerlach Volkman', 'false', 1, 'false', 4, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Trina Willms Gleason', 'false', 5, 'true', 233, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Francisca Spinka Lind', 'false', 3, 'false', 93, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Johnathon Torphy Gusikowski', 'false', 2, 'false', 18, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Gail Bayer Zboncak', 'false', 5, 'true', 104, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Leslee Hyatt Reichert', 'false', 3, 'true', 76, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Jack Collins Ullrich Jr.', 'false', 4, 'true', 40, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('The Hon. Londa Spencer Schuster', 'false', 3, 'false', 38, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Zackary Bayer Kilback', 'true', 4, 'true', 119, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Cleveland Thiel Fay', 'false', 5, 'true', 4, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Eusebio Lubowitz Little', 'true', 2, 'true', 68, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Karin Zemlak Hammes', 'true', 4, 'false', 3, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dino Schimmel Marks JD', 'false', 3, 'true', 124, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Riley Monahan Mann', 'true', 4, 'false', 73, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Bart Stracke Braun', 'true', 5, 'true', 186, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Jesse Armstrong Osinski', 'true', 3, 'false', 34, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Yong Schinner Brakus', 'true', 3, 'true', 67, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Darnell Zulauf Metz', 'false', 2, 'true', 18, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Davis Carter Braun', 'false', 1, 'false', 33, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mr. Goldie Jenkins Wunsch', 'true', 4, 'false', 46, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Cornelia Mohr Ankunding', 'true', 4, 'true', 192, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Armand Hansen Auer', 'true', 2, 'true', 90, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Nina Balistreri Purdy', 'true', 2, 'false', 93, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Prof. Vinita Kerluke Cassin', 'false', 1, 'true', 15, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Kathline Paucek Witting', 'false', 1, 'false', 17, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Leatha Walsh Hodkiewicz', 'true', 3, 'false', 146, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Jimmy Kris Bayer', 'false', 5, 'true', 41, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Blaine Toy Lang IV', 'false', 4, 'true', 143, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Msgr. Minna Herzog Batz', 'true', 3, 'true', 71, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Yer Nikolaus Russel III', 'true', 3, 'false', 62, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Nadine Hilll Kunze II', 'true', 5, 'true', 96, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Luz Blanda Hegmann', 'true', 2, 'true', 17, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hue Donnelly Shields', 'false', 5, 'false', 54, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Alfreda Jacobi Lebsack', 'false', 2, 'false', 25, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Olinda Ruecker Wisozk', 'true', 5, 'true', 204, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Nerissa Boyer Harvey', 'false', 2, 'true', 82, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Micheal Morissette Tremblay', 'true', 2, 'true', 58, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Janis Frami Schroeder', 'true', 2, 'true', 0, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Stewart Goodwin Leffler', 'true', 5, 'false', 125, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Randolph Veum Marquardt', 'false', 5, 'false', 188, (SELECT id FROM cities ORDER BY random() LIMIT 1));
INSERT INTO clients (full_name, phone, birthday_date, has_member_card) VALUES
	('Ricky Bins Hilpert', '+52 (946) 863-4143 x18936', '1965-05-28', 'false'),
	('Gaynelle White Nienow', '+269 1-617-190-1018', '1987-03-15', 'false'),
	('Jeramy Jenkins Mills', '+593 416-013-8931 x05620', '1976-09-19', 'true'),
	('Hui Nicolas Shields', '+290 (906) 979-0478 x84259', '1971-03-01', 'false'),
	('Sol Okuneva Cronin', '+36 1-254-409-8124 x59600', '1988-10-03', 'false'),
	('Roberto Pfeffer Schumm', '+501 (894) 769-1061 x34958', '1973-01-17', 'false'),
	('Mr. Raylene Bartell Beer', '+61-8 (181) 305-4552 x0902', '1958-10-22', 'true'),
	('Ira Gerhold Quitzon', '+234 655-205-2808 x5274', '1976-11-24', 'false'),
	('Al Lowe Funk', '+63 729.055.7187', '1962-11-30', 'true'),
	('Serina Cassin Abbott', '+381 359-053-6250 x4919', '1979-04-30', 'false'),
	('Jamee Kris Skiles', '+1-869 593-861-1608 x16483', '1964-05-03', 'true'),
	('Amb. Anita Ortiz Herzog', '+423 466-005-2272 x52358', '1975-09-20', 'true'),
	('Naida Balistreri Jakubowski', '+670 (205) 015-5101 x17958', '1984-12-15', 'false'),
	('Stan West Fisher', '+1-869 590-492-2842', '1990-10-02', 'true'),
	('Farah Lowe Rutherford', '+850 153.679.5396 x50965', '1986-05-31', 'false'),
	('Fransisca Kerluke Bednar', '+355 (464) 537-1639 x900', '1965-09-19', 'true'),
	('Pres. Tammi Waters Mills', '+231 289.383.6992 x78631', '1993-09-23', 'true'),
	('Ferne Nader Bogisich', '+356 (733) 314-4084', '1958-12-30', 'false'),
	('Phil White Kessler Ret.', '+372 (285) 047-5450 x4116', '1965-03-30', 'true'),
	('Berneice Dibbert Steuber', '+54 (423) 454-0063 x715', '1959-04-06', 'true'),
	('Jovita Mayer Gleason Ret.', '+291 329.050.6753 x889', '1997-03-02', 'false'),
	('Bryon Stokes Walter', '+221 1-436-178-5092', '1984-12-18', 'true'),
	('Dr. Renda Frami Trantow', '+269 1-257-084-3747 x372', '1987-04-06', 'true'),
	('Pres. Rigoberto Swift Runolfsson', '+1-473 (496) 177-4092', '2002-05-27', 'false'),
	('Vicente Ledner Macejkovic I', '+595 (789) 809-7551', '1991-11-30', 'false'),
	('Abe Lubowitz Kunde', '+55 1-230-166-7799', '2001-11-27', 'false'),
	('Twanna Heller Robel Ret.', '+420 446-058-3150 x81686', '1969-03-24', 'true'),
	('Lucien Homenick Ruecker', '+686 769.085.3569', '1962-06-24', 'false'),
	('Else Waelchi Hamill', '+595 439-685-3034', '1997-11-21', 'true'),
	('Juan Bahringer Cummerata', '+421 (821) 826-0061', '2000-07-26', 'false'),
	('Antoine McKenzie Cronin', '+269 1-432-552-8359 x51918', '1972-09-02', 'true'),
	('Sen. Shaun Smitham Ziemann', '+975 1-618-491-7083 x4801', '1985-09-13', 'false'),
	('Marivel Goyette Torp', '+971 (228) 791-6105 x87091', '1982-07-19', 'false'),
	('Crystle Huel Harber', '+691 1-254-922-4522 x36812', '1968-01-15', 'true'),
	('Mohamed Moore Cremin', '+674 766-158-2219', '1970-01-27', 'false'),
	('Bev Braun Koepp', '+225 1-705-771-4646 x40224', '2003-11-25', 'false'),
	('Honey Smith Streich JD', '+593 1-392-478-4880 x4824', '1974-09-13', 'false'),
	('Angel Runolfsson Jones', '+269 1-542-245-0064', '1967-06-23', 'true'),
	('Bruce Vandervort Torp', '+63 1-355-278-1643 x5566', '1986-10-22', 'true'),
	('Michael Upton Gerlach', '+245 (620) 448-5266 x59508', '2003-02-13', 'false'),
	('Rev. Kate Hegmann Koch', '+1-246 1-824-900-9098', '1980-05-21', 'true'),
	('Miss Lovetta Jaskolski Grant', '+381 1-664-547-3005 x8945', '1985-05-04', 'false'),
	('Mellie Morar Legros', '+232 973-773-2564', '1959-05-20', 'true'),
	('Anja Dickinson West', '+1-284 1-798-726-0700 x11692', '1965-01-19', 'true'),
	('Brigitte Funk Lemke', '+1-684 209-509-7867 x636', '1960-12-09', 'true'),
	('Mason Hilll Bernier', '+975 (551) 996-7394 x428', '1964-06-01', 'true'),
	('Hallie Hayes Brown MD', '+235 501-231-8420', '1997-11-14', 'false'),
	('Guillermina Metz Kuvalis', '+596 (779) 685-4626 x93105', '2003-06-29', 'false'),
	('Josiah Abshire Rodriguez', '+218 662.860.7893 x43676', '1967-06-21', 'true'),
	('Brittaney Nicolas Moen JD', '+233 877.059.0531 x7430', '1980-03-22', 'true'),
	('Peter Bradtke Mueller', '+964 1-651-625-3001 x48469', '1958-10-20', 'false'),
	('Kaylee Reichert Hansen', '+213 1-589-365-3349 x37312', '1985-11-16', 'true'),
	('Krista Cassin Gottlieb', '+228 908.234.8287 x01689', '1967-10-28', 'false'),
	('Amb. Amos Schaefer Leuschke', '+672 1-699-631-7963 x7121', '2002-12-03', 'false'),
	('Rep. Digna Kutch Rau', '+84 925.814.6781 x3945', '1962-09-18', 'false'),
	('Rosita Turcotte Kuvalis DC', '+767 764.910.5955 x0764', '1989-01-20', 'true'),
	('Earnestine Lynch Collier', '+886 1-475-565-7415 x7774', '1968-07-18', 'false'),
	('Lane Bailey Mohr', '+683 724.849.7887 x66277', '1985-08-01', 'false'),
	('Jenee Cremin Block', '+385 1-841-685-9250 x392', '1979-07-26', 'true'),
	('Ambrose Bogan Tromp', '+225 1-820-406-6730 x02537', '1983-11-20', 'true'),
	('Bernita Langosh Torp', '+356 1-249-951-1584', '1961-07-02', 'true'),
	('Chas Rowe Beahan', '+39 (356) 728-7761 x45262', '1969-02-03', 'false'),
	('Roma DAmore Braun PhD', '+265 111.140.2315', '2000-05-17', 'false'),
	('Ressie Crist Miller', '+298 841.543.1567 x451', '1987-10-27', 'true'),
	('Gov. Darron Heaney Rodriguez', '+961 464.534.0645', '1989-09-18', 'false'),
	('Jude Hartmann Johnston', '+850 1-876-326-6559 x596', '1985-04-01', 'true'),
	('Jesse Leffler Jacobi', '+229 1-282-635-3168 x70967', '1993-02-09', 'true'),
	('Fr. Kristi Turcotte Rodriguez', '+44 (906) 128-6851 x081', '1964-11-18', 'false'),
	('Adrian Hartmann Barrows', '+212 456-356-5886 x3694', '1974-08-10', 'true'),
	('Gene Considine Leuschke', '+886 1-527-035-5891 x169', '1966-07-10', 'true'),
	('Blake OConner Heller', '+592 500.453.9565 x19406', '1965-02-09', 'false'),
	('Loren Swaniawski Gibson V', '+1-939 1-963-390-6420 x767', '1959-12-17', 'false'),
	('Saul Fay Christiansen', '+36 (165) 994-8899 x204', '1960-11-25', 'true'),
	('Antonio Jacobs OKeefe', '+809 602-917-0813 x6447', '1966-05-09', 'true'),
	('Moon Sauer Bergstrom', '+972 (780) 119-5715 x7138', '1974-09-08', 'true'),
	('Graciela Kirlin Hilll', '+262 207-610-2171 x224', '1997-04-13', 'true'),
	('Eduardo McClure Kshlerin', '+94 267.756.8209 x6128', '1984-08-29', 'false'),
	('Dahlia Purdy Hamill', '+223 (453) 482-4939 x286', '2004-07-12', 'true'),
	('Leanora Powlowski Hegmann', '+964 1-904-276-6608 x063', '1979-11-30', 'true'),
	('Shiloh Dickens Gusikowski', '+381 (489) 579-6227 x5156', '1993-05-24', 'false'),
	('Miss Murray Wunsch Nikolaus', '+809 (136) 892-0060', '1967-05-18', 'true'),
	('Darrick Goyette Reinger', '+594 1-315-136-7237 x9950', '1974-04-13', 'false'),
	('Lida Parisian Klocko', '+353 242-207-3090', '1995-04-22', 'true'),
	('Paris Weber Stark V', '+267 900-417-1910', '1965-08-09', 'false'),
	('Lovella Harvey Kuhlman', '+962 (867) 345-4984 x46561', '1981-11-19', 'false'),
	('Zachary Stroman Donnelly V', '+90 (599) 279-5083 x40478', '1961-08-21', 'true'),
	('Miss Shameka Hickle Wolf', '+974 409.061.2076 x816', '1958-12-13', 'false'),
	('Noble Lueilwitz Tillman DC', '+254 236.277.9576 x4886', '1982-07-18', 'true'),
	('Tori Zboncak Reichert', '+381 (247) 620-7431 x84763', '1996-08-30', 'true'),
	('Ileen Herzog Nolan', '+673 685.152.0865 x857', '1973-05-31', 'false'),
	('Young Cummerata Gislason IV', '+809 1-655-253-3381', '1994-03-29', 'false'),
	('Lucas Purdy Towne', '+974 (987) 056-3645 x62731', '1995-01-06', 'true'),
	('Eugenio Howe Stark III', '+1-345 (555) 734-7379', '1995-02-16', 'false'),
	('Luther Ziemann Fahey MD', '+234 1-974-057-8956 x6680', '1991-01-03', 'false'),
	('Audry Shields Beahan', '+235 375-668-4159 x6816', '1963-08-19', 'false'),
	('Leeanna Johnson Miller', '+20 998.188.0998 x135', '1993-06-28', 'true'),
	('Eustolia OHara Glover', '+267 (698) 238-5914 x90167', '1986-06-05', 'true'),
	('Tiny Bernhard Terry Ret.', '+973 1-459-067-9460 x639', '1998-03-26', 'false'),
	('Bennie Gibson Kutch', '+81 (250) 142-6334 x62403', '2004-10-09', 'true'),
	('Karey Wilkinson Runolfsdottir', '+670 970-736-7661 x021', '1990-10-11', 'true'),
	('Magaret Schaefer Johns', '+856 817.022.7268 x6977', '1990-08-16', 'true');
INSERT INTO flights (price, meal_included, flight_duration,  departure_time, aircompany_id,  departure_airport_id, arrival_airport_id) VALUES
	('2859', 'true', '19', '2023-04-12 06:24:24 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2884', 'true', '1', '2023-04-16 04:30:47 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1969', 'true', '20', '2023-04-15 18:52:14 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('193', 'true', '17', '2023-04-16 15:39:11 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1847', 'false', '5', '2023-04-14 09:58:01 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4524', 'false', '10', '2023-04-14 13:26:03 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('732', 'false', '1', '2023-04-13 10:42:58 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4524', 'true', '2', '2023-04-15 21:29:29 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1870', 'false', '7', '2023-04-10 08:47:09 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1132', 'false', '2', '2023-04-11 09:54:00 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('509', 'false', '5', '2023-04-16 00:28:44 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3936', 'true', '9', '2023-04-13 12:32:15 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1156', 'true', '17', '2023-04-11 05:22:53 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2468', 'true', '3', '2023-04-14 01:18:02 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('989', 'true', '9', '2023-04-15 07:51:08 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('149', 'false', '4', '2023-04-10 16:25:12 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('707', 'false', '13', '2023-04-12 04:55:25 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3032', 'true', '18', '2023-04-11 02:13:41 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4694', 'true', '9', '2023-04-15 03:52:36 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1019', 'false', '16', '2023-04-14 00:54:18 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2053', 'false', '10', '2023-04-16 06:27:33 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2545', 'false', '6', '2023-04-10 01:28:03 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2846', 'false', '6', '2023-04-11 12:05:13 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4255', 'true', '10', '2023-04-13 11:54:28 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4718', 'false', '9', '2023-04-13 04:28:31 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2694', 'false', '19', '2023-04-13 19:42:29 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4523', 'false', '12', '2023-04-15 14:25:48 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2999', 'false', '9', '2023-04-14 03:50:52 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('756', 'false', '10', '2023-04-14 15:23:05 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('108', 'false', '18', '2023-04-11 17:12:08 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2579', 'false', '3', '2023-04-14 19:01:52 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3046', 'true', '10', '2023-04-12 15:33:55 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1808', 'false', '10', '2023-04-10 20:09:14 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1190', 'true', '1', '2023-04-15 13:45:15 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3272', 'true', '4', '2023-04-11 00:04:26 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1752', 'false', '3', '2023-04-10 06:33:51 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('227', 'true', '20', '2023-04-16 04:58:24 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('327', 'false', '10', '2023-04-12 03:03:30 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('311', 'true', '4', '2023-04-15 01:31:31 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1584', 'true', '6', '2023-04-10 16:10:17 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4642', 'false', '13', '2023-04-11 15:26:05 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4105', 'false', '20', '2023-04-12 06:00:08 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('825', 'true', '4', '2023-04-10 20:15:07 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4698', 'false', '11', '2023-04-16 00:26:39 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('547', 'true', '8', '2023-04-13 04:10:24 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4412', 'false', '1', '2023-04-12 19:01:41 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2281', 'false', '15', '2023-04-13 02:42:07 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1670', 'false', '19', '2023-04-15 04:27:04 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2772', 'true', '18', '2023-04-10 11:30:42 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1442', 'false', '1', '2023-04-16 20:23:33 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1001', 'true', '16', '2023-04-10 18:35:55 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('419', 'false', '19', '2023-04-14 23:34:50 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4237', 'true', '6', '2023-04-15 13:24:07 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2496', 'true', '20', '2023-04-11 07:26:10 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2611', 'true', '2', '2023-04-13 03:22:54 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('425', 'true', '8', '2023-04-12 17:24:50 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2403', 'true', '12', '2023-04-14 02:37:36 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2898', 'true', '14', '2023-04-13 21:31:48 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1269', 'false', '1', '2023-04-12 12:12:44 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3488', 'true', '16', '2023-04-15 19:19:29 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4471', 'false', '19', '2023-04-11 18:20:09 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3555', 'false', '6', '2023-04-13 20:14:02 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('653', 'false', '4', '2023-04-15 13:51:46 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('271', 'false', '4', '2023-04-16 20:18:45 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2116', 'false', '20', '2023-04-11 14:25:34 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3023', 'false', '11', '2023-04-15 04:07:12 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1922', 'false', '17', '2023-04-15 18:23:02 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4261', 'true', '17', '2023-04-15 15:06:11 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1007', 'false', '3', '2023-04-11 06:00:05 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2581', 'true', '3', '2023-04-12 16:00:27 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4220', 'false', '17', '2023-04-14 20:32:35 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1822', 'false', '17', '2023-04-11 09:10:55 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4335', 'true', '20', '2023-04-12 21:52:04 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('846', 'false', '8', '2023-04-15 10:31:38 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1033', 'false', '3', '2023-04-14 09:48:29 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('291', 'true', '17', '2023-04-15 23:22:54 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('720', 'true', '6', '2023-04-15 01:56:49 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4529', 'false', '9', '2023-04-10 19:40:03 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2386', 'true', '17', '2023-04-12 13:50:57 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1386', 'true', '1', '2023-04-12 10:03:50 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('43', 'false', '6', '2023-04-16 04:11:30 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2130', 'true', '10', '2023-04-16 06:49:54 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('8', 'true', '1', '2023-04-16 20:12:36 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('644', 'false', '5', '2023-04-16 10:11:07 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3091', 'false', '14', '2023-04-14 15:27:59 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2671', 'false', '6', '2023-04-11 15:19:45 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('984', 'false', '19', '2023-04-10 01:15:59 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3510', 'false', '20', '2023-04-13 01:21:56 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('664', 'false', '17', '2023-04-10 15:14:34 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1524', 'false', '13', '2023-04-15 17:19:16 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4789', 'false', '4', '2023-04-10 11:54:03 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4187', 'false', '3', '2023-04-11 02:49:22 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3284', 'true', '19', '2023-04-14 22:26:10 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3776', 'true', '13', '2023-04-13 00:06:50 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1384', 'false', '8', '2023-04-12 20:42:49 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3484', 'false', '19', '2023-04-15 20:05:18 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2103', 'false', '6', '2023-04-15 01:23:06 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2775', 'false', '9', '2023-04-11 17:11:29 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1553', 'true', '8', '2023-04-15 20:30:37 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2974', 'false', '16', '2023-04-11 00:05:34 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4499', 'false', '15', '2023-04-12 16:43:13 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1));
INSERT INTO trips (departure_flight_id, hotel_id, meal) VALUES
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' );
UPDATE trips SET arrival_flight_id = (SELECT id from flights where flights.departure_time > (SELECT departure_time FROM flights where flights.id = trips.departure_flight_id) ORDER BY random() LIMIT 1),
        departure_date = (SELECT departure_time from flights where flights.id = trips.departure_flight_id );
UPDATE trips SET arrival_date = (SELECT departure_time from flights where flights.id = trips.arrival_flight_id );
INSERT INTO workers (full_name, phone, birthday_date, salary) VALUES
	('Shanika Walsh Barton CPA', '+1-939 937.727.9775', '1998-02-06', 2724),
	('Milo McDermott Johnson', '+39 372.407.6625 x784', '1963-07-25', 4500),
	('Bronwyn Windler Fay III', '+7-7 1-825-376-2817', '1967-01-18', 2192),
	('Mr. Lindsey Schaden Ortiz', '+508 1-304-126-3982 x896', '1978-05-22', 1),
	('Gonzalo Emmerich Zulauf', '+229 106-431-2854 x2569', '1981-05-22', 699),
	('Trinidad Kemmer Reinger', '+358 (797) 365-7574', '1986-01-12', 2489),
	('Elliot Schmidt Schumm', '+855 (148) 295-7873', '1972-04-21', 2056),
	('Carlos Funk Graham', '+963 1-414-355-5870 x8073', '1959-04-09', 4895),
	('Joel Little Marquardt PhD', '+297 1-515-389-1684 x0371', '2003-07-15', 1785),
	('Gov. Birgit Hamill Tillman', '+508 297-561-8565 x93218', '1964-08-13', 1143),
	('Santos Ritchie Cummerata', '+385 821-621-9715 x34786', '1979-08-10', 4050),
	('Leonila Rosenbaum Frami', '+7-7 713-073-6330 x17982', '1982-07-18', 3285),
	('Nicolas Rolfson Kemmer', '+375 120.363.6449 x089', '1996-04-06', 1178),
	('Amb. Celine Reichel Kuhlman', '+380 353-238-9875', '1991-12-09', 4702),
	('Gov. Lionel Lindgren Waters', '+502 (226) 805-4123 x4241', '1968-08-20', 1094),
	('Marcelle Ratke Lemke LLD', '+235 585-572-2844 x15141', '1981-11-19', 3214),
	('Deirdre Grady Auer', '+232 1-745-207-7917 x56528', '1986-08-30', 4286),
	('Etsuko Torphy Brekke', '+381 (345) 945-8629 x88005', '2002-10-09', 2817),
	('Rev. April McKenzie Donnelly', '+52 371.885.2844', '1996-03-19', 1000),
	('Amb. Loretta Runolfsdottir Cormier', '+297 621-890-9319', '1976-03-02', 2078),
	('Quentin Lehner Frami', '+1-671 (182) 099-0339 x4542', '1994-08-10', 3366),
	('Ricky Balistreri Hilll', '+269 982-087-7778 x75826', '2003-12-30', 4843),
	('Rep. Dylan Kohler Bernier', '+596 1-750-263-2808 x5664', '1993-12-19', 1794),
	('Scotty Wuckert Daugherty', '+964 493-358-9005 x07218', '1988-03-12', 4354),
	('Celina Borer Gibson', '+91 (163) 427-1081 x94452', '2000-05-21', 910),
	('Dana Daniel Kuhn', '+256 1-556-226-0126 x41363', '1978-01-29', 2233),
	('Odell Ullrich Altenwerth', '+372 419.957.8337 x1171', '1980-05-27', 3369),
	('Prince Mraz Armstrong', '+673 (582) 450-1509 x15993', '1980-07-14', 4541),
	('Britt Keeling Moen', '+376 1-690-927-5038 x801', '1958-05-27', 1216),
	('Kimi Muller Sauer', '+33 866-243-6826 x991', '1992-10-31', 4594),
	('Gisela Gulgowski Hammes', '+297 (172) 225-7896 x7840', '2000-01-09', 3536),
	('Fr. Vita Dietrich Kautzer', '+212 1-578-002-7662 x2247', '1962-09-08', 592),
	('Belle Hermiston Fahey', '+247 486.195.7602', '1973-04-18', 3410),
	('Landon Dicki Ward LLD', '+7-6 412.925.7107 x61931', '2002-01-09', 4802),
	('Kelley Wunsch Marks', '+1-869 1-955-617-9055', '2004-10-28', 4971),
	('Lenard West Brekke', '+51 (298) 166-9488 x92849', '1976-02-07', 2004),
	('Marlin Emmerich Marks JD', '+93 223-590-0501', '2003-05-05', 3439),
	('Jacquelyne Macejkovic Pagac', '+216 1-946-337-0996 x26878', '1965-02-08', 1870),
	('Dr. Colton Turcotte Gorczany', '+1-340 (444) 241-3086 x3790', '2001-10-25', 413),
	('Gov. Elisha Borer Labadie', '+223 894.630.5401 x5398', '1994-07-23', 1380),
	('Kurt Schuster Tillman', '+670 (155) 367-8569 x8725', '2002-06-12', 977),
	('Diamond OConnell Kuhn', '+688 590.647.4672 x526', '2003-04-26', 4386),
	('The Hon. Reita Tromp Murazik', '+855 769.112.6723 x43289', '1985-02-05', 3142),
	('Azalee Heller Turner', '+221 (333) 790-6945', '1961-10-19', 1937),
	('Alison Price Cremin', '+355 (664) 318-7671 x37334', '1980-08-23', 364),
	('Carlyn Waelchi Bernier', '+592 442-981-6854 x73842', '2001-05-22', 4891),
	('Prof. Gene OHara DuBuque', '+290 (999) 887-3717 x6492', '1985-09-15', 3549),
	('Delbert Lakin Abbott', '+676 298-375-4658 x656', '1999-03-24', 2218),
	('Shaquita Schaefer Heller Sr.', '+27 831-889-7863 x23681', '1993-10-29', 3936),
	('Cary Hintz Ziemann', '+61-8 (615) 635-5776 x122', '1979-04-29', 3969),
	('Fannie Stracke Morissette', '+350 (296) 779-1645', '1977-03-02', 3465),
	('Anastacia McDermott Olson', '+1-784 1-609-474-0645', '2001-01-18', 1027),
	('Yasuko Stokes Durgan', '+48 484-751-8627', '1967-12-30', 2083),
	('Mr. Stanley Toy Reichert', '+674 (673) 937-0748 x35944', '1965-11-03', 2963),
	('Edward Zulauf Lind Ret.', '+93 618-291-1049 x689', '1997-11-04', 3360),
	('Pamelia Tromp Jast', '+299 (110) 488-9193 x179', '1984-09-18', 3591),
	('Napoleon Schneider Kiehn', '+1-242 1-848-387-6699 x39777', '1962-10-26', 4486),
	('Beverlee Hilll Kunze', '+507 1-726-585-9073', '1986-11-05', 4343),
	('Christopher OHara Schmeler', '+251 438.047.3079', '1974-02-10', 1353),
	('Marc Gleason Kreiger Jr.', '+63 (285) 740-8772 x7045', '1968-04-11', 3257),
	('Kent Mohr Greenfelder', '+599 1-987-724-2056', '1972-08-29', 4334),
	('Georgene Lowe Aufderhar', '+39 1-119-219-7259', '1998-07-11', 1199),
	('Davis Zboncak Jones', '+245 683.873.0576', '1987-09-03', 136),
	('The Hon. Shizue Feeney Heller', '+238 703.463.6670 x24471', '1993-01-01', 4031),
	('Teodoro Douglas Ryan', '+966 757-280-0442 x8616', '1966-07-23', 178),
	('Fr. Jeffery Mosciski Lakin', '+212 (684) 173-2541 x850', '1979-07-26', 4201),
	('Mervin Hahn Kreiger', '+240 916.465.5114', '2002-05-19', 20),
	('Sen. Melvin Anderson Hirthe', '+677 (151) 991-6427 x13836', '1984-03-07', 4348),
	('Liana Klein Botsford', '+809 980-933-3693 x622', '1990-10-06', 4319),
	('Lakisha Pagac Hills Jr.', '+1-876 1-248-231-7507 x11785', '1994-09-13', 2093),
	('Harvey Pouros Ward', '+250 736.721.5303 x26315', '1969-02-06', 4245),
	('Elvin Schulist Pagac DC', '+966 719-718-8576 x22347', '1998-06-16', 906),
	('Shelby Murazik Wilkinson', '+809 793-643-7645 x55617', '1987-12-26', 4581),
	('Otto Quitzon Gerhold', '+389 1-307-422-0484 x893', '1961-09-11', 1109),
	('Melina Ledner Block', '+966 (921) 743-3522 x36217', '1967-04-20', 2657),
	('Moses Gorczany Cummerata', '+20 (546) 983-0094 x45521', '1992-11-28', 4717),
	('Dr. Lala Davis Nicolas', '+960 (878) 551-8777', '1958-05-16', 2796),
	('Curtis Yundt Rolfson DDS', '+357 (742) 484-6641 x4781', '1962-10-16', 971),
	('Shirl Brekke Schneider', '+502 900-727-6181 x892', '1973-03-04', 1618),
	('Gov. Curt Kovacek Wunsch', '+232 328.496.9008 x9786', '1973-08-06', 3588),
	('Miss Eleanor Smitham Grady', '+229 (375) 044-7124 x742', '1991-11-30', 712),
	('Arica Treutel Treutel DC', '+53 (532) 059-0201 x627', '1979-03-16', 4919),
	('Isiah Waters Dach', '+509 (768) 054-7973 x17510', '1999-12-30', 287),
	('Epifania Beatty Satterfield', '+683 962.478.5511', '1968-03-24', 3356),
	('Margarette Stoltenberg Rippin III', '+1-876 993.189.9844', '1973-07-29', 1493),
	('Terica Beer Hauck', '+53 (715) 549-2329', '1995-09-13', 2858),
	('Amb. Sherman Considine Kling', '+968 176-270-1708', '1996-12-09', 3861),
	('Timika Little Fahey', '+505 350.733.5495 x37932', '1991-01-16', 2881),
	('Miss Foster Brekke Hagenes', '+239 1-471-863-9243', '1984-04-12', 4698),
	('Ranae Huels Erdman', '+996 522-211-0358 x0915', '1996-07-25', 1441),
	('Merna Leannon Kuvalis', '+686 472.584.6931 x93957', '1977-11-02', 4401),
	('Stephane Considine Labadie I', '+268 (915) 361-1035', '1977-09-30', 4699),
	('Brigid Adams DAmore', '+82 (791) 055-5680', '1978-06-06', 3964),
	('Mitchel Dickinson Stoltenberg', '+1-473 (952) 392-4299 x307', '1962-02-17', 1659),
	('Edmund Goyette Ledner', '+41 1-537-966-0458 x2613', '1981-03-05', 1763),
	('Fr. Lavina Abshire Donnelly', '+221 951.615.4648 x61754', '1998-02-04', 4213),
	('Sung Hamill Schaefer', '+7 (400) 011-9699 x389', '1968-06-14', 3144),
	('Meri Moore Mraz', '+1-670 967-898-9487 x8842', '1960-11-14', 1293),
	('Percy Lemke Macejkovic', '+244 365-831-8282 x98899', '2002-05-13', 2275),
	('Casey Jaskolski Goodwin', '+1-242 1-785-842-1000', '2002-08-19', 1896),
	('Vince Stroman Hammes CPA', '+975 1-357-900-4191 x699', '1995-09-15', 4334);
