INSERT INTO aircompanies (name) VALUES
	('Stehr LLC'),
	('Tromp-Kreiger'),
	('Leannon Inc'),
	('Robel-Simonis'),
	('Stoltenberg LLC'),
	('Feeney, Ebert and Emmerich'),
	('Feeney Group'),
	('Zulauf-Dickens'),
	('Baumbach-Klocko'),
	('Nader, Towne and Mayert'),
	('Adams, Smitham and Mayert'),
	('Kub Inc'),
	('Bednar-Rempel'),
	('Kertzmann Inc'),
	('Langosh Inc'),
	('Mertz LLC'),
	('Barrows, Ferry and Hermann'),
	('Labadie-Daniel'),
	('Wilkinson LLC'),
	('Gerlach Inc'),
	('Rau Inc'),
	('Cronin, Aufderhar and Grady'),
	('Ratke Inc'),
	('Murphy-Schaefer'),
	('Corkery, Hammes and Crona'),
	('Lindgren-Walker'),
	('Schaden and Sons'),
	('McGlynn-Stoltenberg'),
	('Haag and Sons'),
	('Swaniawski-Jerde'),
	('Ryan-Stracke'),
	('White-Rosenbaum'),
	('Hayes-Prohaska'),
	('Spencer LLC'),
	('Hagenes Group'),
	('Graham, Schultz and Wolff'),
	('Koch, Brekke and Kozey'),
	('Jacobson, Walsh and Cremin'),
	('Crooks, OConner and Thompson'),
	('Marks Inc'),
	('Stiedemann, Roob and Stark'),
	('Hackett-Padberg'),
	('West Group'),
	('Wolff LLC'),
	('Zulauf-Schmidt'),
	('Bernier, Franecki and Wiegand'),
	('Pagac-Labadie'),
	('Pacocha-Gusikowski'),
	('Gusikowski, McCullough and Gutmann'),
	('Jones Inc'),
	('Block, Schuster and Brakus'),
	('MacGyver and Sons'),
	('Luettgen-Walter'),
	('Blick, Torp and Bruen'),
	('Pfeffer-MacGyver'),
	('Keeling LLC'),
	('Kertzmann-Lind'),
	('Bins, Homenick and Jacobson'),
	('Bartoletti-Klein'),
	('Ward Group'),
	('Grimes-Stokes'),
	('Grimes, Sipes and Kutch'),
	('Daniel-Maggio'),
	('Hoeger, Bergstrom and Kunde'),
	('Stanton, Conroy and Franecki'),
	('Wisoky-Volkman'),
	('Ortiz, Pfannerstill and Wilderman'),
	('Fritsch Group'),
	('Ritchie, Fahey and Schulist'),
	('McClure, Jacobi and Jacobs'),
	('Medhurst and Sons'),
	('Durgan-Hegmann'),
	('Renner, Hauck and Gutmann'),
	('Gottlieb Group'),
	('Wolff, Lehner and Cassin'),
	('Rohan Group'),
	('Barton-Willms'),
	('Watsica, Borer and Cassin'),
	('Bednar, Bailey and VonRueden'),
	('Rolfson-Lind'),
	('Adams-Hessel'),
	('Harber and Sons'),
	('Schaefer, Ward and Upton'),
	('Collier, Jakubowski and Stroman'),
	('Stark Group'),
	('Strosin Inc'),
	('OConner Group'),
	('Lynch-Heidenreich'),
	('Donnelly, Monahan and Cruickshank'),
	('Fahey Group'),
	('Lueilwitz, Reichel and Kihn'),
	('Bosco, Walsh and Goldner'),
	('Murazik, Hauck and Lesch'),
	('Jenkins LLC'),
	('Collier, Hickle and Nikolaus'),
	('Stroman and Sons'),
	('Armstrong, Hermiston and Hickle'),
	('Streich, Beatty and Bayer'),
	('Gusikowski, Howe and Oberbrunner'),
	('Larson Group'),
	('Boyer, Marvin and Harber');
INSERT INTO countries (name) VALUES
	('Chad'),
	('Sweden'),
	('Gabon'),
	('French Southern Territories'),
	('Thailand'),
	('Tuvalu'),
	('French Polynesia'),
	('Jamaica'),
	('Niger'),
	('Virgin Islands, U.S.'),
	('Peru'),
	('Sudan'),
	('India'),
	('Sierra Leone'),
	('New Zealand'),
	('Malaysia'),
	('Bulgaria'),
	('Botswana'),
	('Italy'),
	('Greenland'),
	('Comoros'),
	('Vietnam'),
	('France'),
	('Armenia'),
	('Japan'),
	('Costa Rica'),
	('Venezuela'),
	('Kyrgyz Republic'),
	('Fiji'),
	('Canada'),
	('Mongolia'),
	('Oman'),
	('Iraq'),
	('Liberia'),
	('Norfolk Island'),
	('Norfolk Island'),
	('Senegal'),
	('Jamaica'),
	('Nepal'),
	('Italy'),
	('Faroe Islands'),
	('Georgia'),
	('Lithuania'),
	('Ecuador'),
	('Cape Verde'),
	('Niger'),
	('Gambia'),
	('Martinique'),
	('Cocos (Keeling) Islands'),
	('Vanuatu'),
	('Virgin Islands, British'),
	('Antigua and Barbuda'),
	('Austria'),
	('Taiwan'),
	('Botswana'),
	('Tanzania'),
	('Burkina Faso'),
	('Greenland'),
	('Zimbabwe'),
	('Yemen'),
	('Bahamas'),
	('Benin'),
	('Namibia'),
	('Congo'),
	('Liberia'),
	('Sudan'),
	('Congo'),
	('Wallis and Futuna'),
	('Turkey'),
	('Chad'),
	('Netherlands'),
	('Saint Barthelemy'),
	('Brunei Darussalam'),
	('Burkina Faso'),
	('Tokelau'),
	('Cocos (Keeling) Islands'),
	('Bahamas'),
	('Montenegro'),
	('Togo'),
	('Bolivia'),
	('Nepal'),
	('Poland'),
	('Saint Barthelemy'),
	('Isle of Man'),
	('Yemen'),
	('New Caledonia'),
	('Reunion'),
	('Dominica'),
	('Germany'),
	('Bhutan'),
	('Bulgaria'),
	('French Guiana'),
	('Sri Lanka'),
	('Finland'),
	('Argentina'),
	('Netherlands'),
	('Niger'),
	('Norway'),
	('Greece'),
	('American Samoa'),
	('Waelchi-Nikolaus');
INSERT INTO cities (name, country_id) VALUES
	('Emelineborough', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Gladys', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Valentinechester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Creminberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Hellerborough', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Trantowport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Jordanville', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Bettiechester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Stantonville', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Julia', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Johnsmouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Yesseniastad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Terrenceland', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Roweland', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Myungtown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Robbitown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Hal', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Josephberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Dickimouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Orlandochester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Cordellmouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Arletha', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Shieldsview', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Feestbury', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Larraine', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Chaseville', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Mapleborough', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Morgantown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Misti', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Venessa', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Wilfredville', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Leighberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Cyndiport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Cassidystad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Ferryside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Celinda', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Mylesport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Alicetown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Yundthaven', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Altheaville', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Ladawnport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Vince', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Hansentown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Volkmanmouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Hudsonchester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Alfonsoside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Eusebioberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Aishaview', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Wallace', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Elaview', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Edelmira', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Marcelo', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lynchfort', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Bartonchester', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Goodwinmouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Tremblayside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Zachariahtown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Irvinland', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Lawandatown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Octaviomouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Marcelostad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Vida', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Marcosborough', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Douglasland', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Aletabury', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Lelaport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Eladiafort', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Maurice', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Venetta', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Sharriburgh', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Heidi', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Cecillemouth', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Raynastad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Steffanieville', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Fadelshire', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Borerberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Jospehton', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Rupertland', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Mari', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Port Desmondstad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lynellestad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Genaro', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Nikolauston', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Agustinborough', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Greggtown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Dianna', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('West Burtonstad', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Lucio', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Ziemeview', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Carinaberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Celinetown', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Gustavoport', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('East Donnetteberg', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Manteshire', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Trompbury', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('North Tressafurt', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Dagmar', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('South Cleoborough', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Lake Fawnside', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('New Parkerfort', (SELECT id FROM countries ORDER BY random() LIMIT 1)),
	('Altenwerth, Herzog and Heaney', (SELECT id FROM countries ORDER BY random() LIMIT 1));
INSERT INTO airports (name, city_id) VALUES
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Logan International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('John F. Kennedy International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Seattle Tacoma International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hartsfield Jackson Atlanta International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('George Bush Intercontinental Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tampa International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hartsfield Jackson Atlanta International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('LaGuardia Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ronald Reagan Washington National Airport**', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('George Bush Intercontinental Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Phoenix Sky Harbor International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Orlando International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Detroit Metropolitan Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Francisco International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Daniel K. Inouye International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Logan International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Harry Reid International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Salt Lake City International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Orlando International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('OHare International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Harry Reid International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Seattle Tacoma International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('John F. Kennedy International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('John F. Kennedy International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Baltimore/Washington International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Orlando International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Philadelphia International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('LaGuardia Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Midway International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('John F. Kennedy International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Phoenix Sky Harbor International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Orlando International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Diego International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Minneapolis Saint Paul International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Phoenix Sky Harbor International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Denver International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Harry Reid International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Harry Reid International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Logan International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Phoenix Sky Harbor International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('LaGuardia Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Francisco International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Minneapolis Saint Paul International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Denver International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Logan International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Midway International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('John F. Kennedy International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Logan International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Newark Liberty International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Salt Lake City International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Diego International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Minneapolis Saint Paul International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Charlotte Douglas International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('George Bush Intercontinental Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Detroit Metropolitan Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Orlando International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hartsfield Jackson Atlanta International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Portland International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Phoenix Sky Harbor International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dulles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Daniel K. Inouye International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('George Bush Intercontinental Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Newark Liberty International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('George Bush Intercontinental Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Los Angeles International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Midway International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Salt Lake City International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Daniel K. Inouye International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ronald Reagan Washington National Airport**', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dallas/Fort Worth International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hartsfield Jackson Atlanta International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fort Lauderdale Hollywood International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('George Bush Intercontinental Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Midway International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miami International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('San Diego International Airport', (SELECT id FROM cities ORDER BY random() LIMIT 1));
INSERT INTO hotels (name, has_pool, number_of_stars, cleaning_included, price_for_a_person, city_id) VALUES
	('Alphonso Weimann Mohr', 'true', 3, 'true', 82, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Nadine Kiehn Wilderman', 'false', 1, 'true', 8, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Breann VonRueden Huels', 'false', 2, 'false', 76, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Valentin Heidenreich Marquardt', 'true', 4, 'false', 42, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Sung Will Bechtelar', 'false', 4, 'true', 150, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Lorenzo Lakin Schiller', 'true', 3, 'false', 6, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('The Hon. Lieselotte Feeney Greenfelder', 'true', 2, 'false', 38, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Meghan Flatley Frami', 'true', 3, 'false', 57, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Gus Sporer Hahn', 'false', 1, 'true', 49, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Frankie Brown Towne', 'true', 3, 'false', 69, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Caleb Von Little', 'false', 4, 'true', 61, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Rickie Ebert Sawayn', 'true', 1, 'true', 12, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Issac Konopelski Gusikowski', 'false', 2, 'false', 27, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Rena Okuneva Schmeler', 'true', 4, 'true', 65, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Marcos Miller Hahn', 'true', 1, 'false', 46, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mr. Ginger Beahan Pfannerstill', 'true', 4, 'true', 167, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dr. Rasheeda Kiehn Jerde', 'true', 1, 'false', 27, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Stanley Koss Koepp', 'false', 3, 'true', 120, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Miesha Strosin Senger', 'true', 3, 'false', 4, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Vernia Schuster Berge', 'true', 1, 'true', 7, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Edwin Wilkinson Satterfield', 'true', 3, 'false', 66, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Frank Rempel Russel', 'false', 5, 'false', 102, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Marry Schaden Parker', 'false', 4, 'true', 45, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Janyce Mayer Mosciski', 'false', 3, 'true', 108, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Msgr. Corey Mraz Boehm', 'false', 4, 'false', 17, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ira Tremblay Robel', 'false', 1, 'false', 36, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Pamila Schumm Rath', 'true', 4, 'false', 42, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Dwight Ankunding Konopelski', 'false', 1, 'false', 47, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Arcelia Moore Zulauf', 'false', 1, 'false', 23, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Kaley Aufderhar Braun', 'false', 1, 'false', 43, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Rev. Brad Keebler Mante', 'false', 1, 'false', 19, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Sen. Blossom Bruen Strosin', 'false', 2, 'false', 88, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mr. Daine Kohler Ferry', 'true', 1, 'false', 41, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Hertha Muller Kiehn', 'false', 5, 'true', 25, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Gov. Delena Moore Parisian', 'false', 3, 'false', 144, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Noel Kihn Yundt', 'true', 3, 'true', 115, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Marcelo Renner Schumm', 'true', 4, 'true', 182, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Carola Macejkovic Lang', 'false', 3, 'true', 27, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Coretta Bernhard Rippin', 'true', 2, 'true', 49, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Meagan Feil Heathcote', 'false', 2, 'true', 66, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Foster Emmerich Bahringer', 'false', 1, 'true', 15, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Season Kub Upton', 'false', 5, 'true', 121, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Sarai Crooks Langosh', 'false', 5, 'true', 30, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Isabelle Gottlieb Watsica', 'false', 2, 'true', 17, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Leota Feest Schuster', 'false', 5, 'false', 63, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Prof. Rickey Price Macejkovic', 'true', 3, 'true', 15, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Kenneth Renner Satterfield PhD', 'true', 2, 'false', 20, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Aaron Kunde Mosciski', 'false', 2, 'false', 69, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Horacio Hoppe Kling', 'true', 3, 'true', 73, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fred MacGyver Champlin', 'true', 5, 'true', 213, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mrs. Michale Bernhard Langworth', 'true', 1, 'true', 9, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Lorina Funk Bosco', 'false', 3, 'false', 8, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Chadwick VonRueden Mante', 'true', 3, 'false', 41, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Gov. Lane Grimes Hodkiewicz', 'true', 1, 'false', 25, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Rickie Ullrich Runolfsson', 'true', 1, 'true', 40, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Nguyet OReilly Wiza', 'true', 5, 'false', 180, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Milan Bauch Barrows', 'false', 3, 'false', 56, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Paula Klocko Jenkins DC', 'false', 2, 'false', 85, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Juan Windler Stanton', 'true', 5, 'true', 208, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Gov. Piper Legros Cummerata', 'true', 2, 'false', 27, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Zane Bins Kerluke', 'false', 5, 'false', 160, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Iraida Rath Cummerata', 'true', 5, 'true', 53, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Elida Harvey Osinski IV', 'true', 2, 'true', 92, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Darwin McGlynn Ferry DVM', 'true', 1, 'true', 46, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Emile Stracke Emard', 'true', 4, 'true', 29, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Horace Tremblay Gislason', 'true', 1, 'true', 24, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mr. Sharlene Rolfson Hayes', 'false', 1, 'false', 7, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Tressie Dare Ullrich', 'true', 4, 'false', 150, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Nisha Padberg OReilly', 'true', 5, 'true', 86, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Wilber Sipes Wisozk', 'true', 3, 'true', 56, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Chanel Gerhold Robel', 'true', 2, 'false', 45, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mrs. Beverlee McKenzie Rohan', 'false', 3, 'false', 127, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Gov. Hugo Breitenberg Windler', 'true', 3, 'true', 105, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Laine White Prohaska', 'false', 2, 'true', 88, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Salley Hodkiewicz Rutherford Jr.', 'true', 4, 'false', 177, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Amb. Bernard Reynolds Fahey', 'true', 3, 'true', 108, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fe Runte Feeney', 'false', 5, 'false', 185, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Daren Gibson Dietrich', 'true', 3, 'true', 8, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Denis Wisozk Murray', 'false', 3, 'false', 95, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Gwendolyn Dicki Runolfsson', 'false', 1, 'true', 31, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Rep. Avril McKenzie Emmerich', 'true', 1, 'true', 17, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ozzie West Tillman Jr.', 'false', 5, 'false', 60, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ms. Camellia Krajcik Barrows', 'false', 3, 'false', 74, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Patricia Braun Cassin PhD', 'true', 1, 'false', 49, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Juan Pagac Lehner', 'true', 1, 'true', 20, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Wilber Pouros Hoppe I', 'false', 2, 'true', 47, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Fr. Sibyl Reilly Mraz', 'true', 1, 'false', 13, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Sen. Raymond Lebsack Nitzsche', 'false', 1, 'true', 34, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Diedre Bernier Powlowski', 'false', 1, 'true', 31, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mrs. Kanesha Rowe Barrows', 'true', 3, 'true', 92, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Layne Beer Mueller', 'false', 2, 'true', 78, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Rodrigo Christiansen Funk', 'false', 5, 'false', 232, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Lucien Leffler Smitham', 'false', 5, 'true', 147, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Corine Dach Frami I', 'false', 2, 'true', 98, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mr. Reginald Terry Krajcik', 'false', 2, 'true', 88, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Alfredo Oberbrunner Moen', 'true', 1, 'false', 2, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Kiley Steuber Sporer LLD', 'false', 3, 'true', 69, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Mr. Gerry Fritsch Sanford', 'true', 5, 'true', 6, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Jess Kunde Swaniawski', 'true', 4, 'false', 181, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Ms. Leigh Walter Ortiz', 'true', 2, 'false', 30, (SELECT id FROM cities ORDER BY random() LIMIT 1)),
	('Pres. Len Boyer Hyatt', 'true', 5, 'false', 160, (SELECT id FROM cities ORDER BY random() LIMIT 1));
INSERT INTO clients (full_name, phone, birthday_date, has_member_card) VALUES
	('Genaro Hagenes Mohr', '+682 1-532-170-7563 x850', '1982-12-23', 'true'),
	('Taylor Reilly Franecki', '+242 (566) 613-8696', '1963-11-03', 'true'),
	('Katherina Stroman Ritchie', '+966 1-371-412-3769', '1995-11-04', 'false'),
	('Wendell Waelchi Sporer', '+1-671 579.530.2598 x2268', '2005-03-19', 'true'),
	('Miss Katina Bergnaum Crona', '+1-649 1-787-876-5667 x38107', '1970-07-29', 'true'),
	('Msgr. Vernon Yundt Schowalter', '+973 894.712.6110 x79823', '1973-08-20', 'true'),
	('Granville Hand Nitzsche', '+58 1-827-455-0640 x856', '2005-03-24', 'true'),
	('Garry Rempel Metz', '+298 1-646-002-4344', '1989-09-08', 'false'),
	('Ray Friesen Bergstrom', '+98 (520) 581-2945', '1961-12-07', 'false'),
	('Hermina Block Raynor', '+222 995-198-0256', '1973-08-04', 'true'),
	('Claudette Miller Nicolas DVM', '+375 652.814.4810 x1050', '1970-05-09', 'false'),
	('Weston Oberbrunner Weissnat', '+350 947-707-1369 x39555', '1997-09-30', 'false'),
	('Lovella Towne Nicolas', '+677 (958) 046-8838 x41954', '1986-08-19', 'false'),
	('Sammy Bergstrom Heaney', '+265 (282) 060-4087 x91770', '1995-03-18', 'false'),
	('Johnnie Grady Bode', '+238 (577) 474-3137', '1998-09-17', 'true'),
	('Michelina Ondricka Torphy PhD', '+681 471-390-1062 x89534', '1996-10-09', 'false'),
	('Wenona Cremin Kuvalis PhD', '+595 1-852-752-0814', '2004-09-14', 'false'),
	('Huey Harber Lakin VM', '+886 384-432-7244 x9633', '1968-01-09', 'false'),
	('Charissa Hartmann Murphy', '+681 1-782-654-1578 x62642', '1967-12-06', 'false'),
	('Floyd Wiegand Stoltenberg', '+1-670 (696) 245-6756 x562', '2000-01-10', 'true'),
	('Maxine Carroll Wisoky', '+212 1-294-859-3770 x215', '1959-10-12', 'true'),
	('Bradford Larkin Ruecker MD', '+60 463.899.6364 x066', '1993-07-20', 'true'),
	('Malika Cummerata Thiel DDS', '+374 277.128.8593', '1990-10-20', 'false'),
	('Miquel Erdman Harber', '+507 1-197-540-4949 x215', '1990-08-21', 'true'),
	('Logan Padberg Mohr', '+45 (521) 914-3909', '2002-05-11', 'true'),
	('Mrs. Maurice Beahan Koelpin', '+675 460-630-0471 x96406', '1978-04-28', 'true'),
	('Shan Frami Vandervort', '+977 264.952.0269 x80639', '1965-03-13', 'false'),
	('Brant Collins Klein', '+228 434.930.7434 x878', '1981-06-04', 'false'),
	('Berniece Cartwright Carter IV', '+52 509.514.0975', '2003-08-28', 'false'),
	('Dorsey Nikolaus Fisher', '+91 712.609.8946 x08071', '1980-03-12', 'true'),
	('Alfonzo Leffler Daniel', '+51 396.270.1503 x97472', '1971-08-27', 'true'),
	('Alonzo Swift Kuvalis', '+509 331-961-8484 x6008', '1966-11-09', 'true'),
	('Summer Swift Ebert IV', '+54 1-578-454-5470 x408', '1981-03-20', 'false'),
	('Madlyn Kihn Goldner', '+1-671 (859) 605-6644 x209', '1974-02-19', 'false'),
	('Arlene Goldner Schmeler', '+852 (414) 260-5061 x34864', '1992-11-08', 'false'),
	('Karolyn Mayert Macejkovic', '+591 1-219-933-6062 x47895', '1985-07-15', 'true'),
	('Shon Kuhic Quigley', '+81 606.978.9618 x35287', '1971-03-26', 'false'),
	('Yulanda Hudson Gibson', '+258 215.721.1702 x103', '2004-10-27', 'false'),
	('Lauralee Hudson Wehner', '+670 144.493.6089 x6580', '1983-06-18', 'true'),
	('Hollis Volkman Witting', '+596 1-308-556-5349 x422', '1996-05-08', 'true'),
	('Casey Mosciski Kunze', '+386 575.634.6211 x08138', '1976-05-25', 'true'),
	('Sue Mitchell Schmeler', '+683 1-501-467-8094', '1979-01-24', 'true'),
	('Gil Cronin Gutmann', '+262 1-379-575-3735 x5116', '1988-03-27', 'false'),
	('Rev. Carrol Emmerich Grady', '+60 1-963-833-6016 x882', '1992-06-20', 'true'),
	('Kim Berge Mohr', '+692 498-272-2195 x13875', '1995-06-13', 'false'),
	('Tisha Padberg Schamberger', '+502 241.519.3928 x17437', '1972-08-07', 'true'),
	('Melinda Schroeder Kling', '+1-939 213-163-8943 x575', '2005-04-02', 'false'),
	('Fausto OKon Bailey', '+996 (600) 052-1051 x6204', '1972-08-07', 'true'),
	('Ariel Wilkinson Schroeder', '+373 (246) 012-3541 x456', '1963-01-20', 'true'),
	('Hoyt Powlowski Turner', '+221 822.363.7536 x55409', '1979-09-14', 'true'),
	('Ashley Skiles Weimann', '+55 378.924.4184 x15716', '1964-12-16', 'true'),
	('Albertha Rippin MacGyver', '+359 (589) 826-0693 x4853', '1963-01-16', 'false'),
	('Leighann McKenzie Stamm V', '+98 410-683-7254 x0585', '1990-07-17', 'false'),
	('Miss Danelle Turcotte Dickinson', '+228 (582) 363-2613 x554', '1978-01-26', 'true'),
	('Helena Kuhic Padberg', '+373 (990) 206-4607 x392', '1966-11-10', 'false'),
	('Lan Brekke Farrell IV', '+386 1-262-001-8197', '1976-04-22', 'false'),
	('Hipolito Block Wiza', '+373 521.952.0319 x86230', '1981-12-18', 'false'),
	('Jillian Mertz Padberg MD', '+381 1-715-187-4131 x6107', '1997-06-08', 'true'),
	('Bennett Wiegand Conroy', '+91 896-151-5764', '1996-11-24', 'false'),
	('Sharon Howe Bosco', '+1-876 270.998.3472 x0508', '1986-03-13', 'false'),
	('Tyron Dickens Stark', '+34 241.842.6265', '1992-08-17', 'false'),
	('Laurence Wiegand Wintheiser', '+355 625.183.5425 x824', '2004-12-28', 'false'),
	('Brady Turner Stiedemann I', '+253 131-470-9380', '2001-09-02', 'false'),
	('Dwana Keeling Hane V', '+229 1-552-837-7661 x30633', '1975-11-14', 'true'),
	('Venita Huel Okuneva MD', '+95 631.190.3576 x62509', '1964-05-20', 'false'),
	('Elicia Bashirian Erdman Jr.', '+964 1-274-664-5478 x71404', '1975-02-10', 'true'),
	('Ms. Olimpia Pouros Von', '+218 434-341-1706 x1959', '1984-07-05', 'false'),
	('Titus Stoltenberg Mraz', '+689 (979) 097-0288 x3286', '1978-08-10', 'true'),
	('Karri Rosenbaum Becker', '+45 885-943-9951 x75401', '1996-12-25', 'false'),
	('Nu Braun McKenzie Ret.', '+855 791-097-2711 x0562', '1974-04-05', 'false'),
	('Pedro Ward Stracke', '+682 1-931-849-9927 x127', '1994-12-22', 'true'),
	('Viola Marquardt Quigley', '+595 499-085-4221 x356', '1998-07-31', 'false'),
	('Rev. Al Ritchie Feil', '+232 909.081.5618', '1976-11-14', 'true'),
	('Samual Hahn Kutch', '+504 727.169.6390 x3935', '2002-11-11', 'true'),
	('Lizabeth Ritchie Lakin', '+509 760-290-9352 x151', '1966-08-21', 'true'),
	('Miss Rea Quigley Muller', '+291 (411) 098-6807 x110', '2003-01-20', 'true'),
	('Michaele Hodkiewicz Moen', '+242 1-198-910-8697 x434', '1963-04-20', 'false'),
	('Clifford Corkery Yundt', '+961 124-270-7192 x9531', '1960-03-24', 'false'),
	('Dick Reichel Langworth', '+224 789.226.7754', '1988-04-30', 'false'),
	('Amb. Hellen Connelly Jones', '+351 (394) 959-4698 x29596', '1970-06-27', 'false'),
	('Raymundo Rosenbaum Wilderman V', '+1-264 779-065-6625', '1966-08-02', 'false'),
	('Carmelo Bernier Ondricka', '+225 1-244-366-6661 x27784', '1982-06-12', 'true'),
	('Kyle Dickinson Pfeffer', '+1-268 1-471-983-2528 x488', '2002-11-09', 'false'),
	('Curtis Reilly Satterfield', '+252 643-758-2952 x62758', '1981-06-26', 'true'),
	('Riley Brekke Lakin', '+298 1-973-652-2423 x74640', '1995-06-26', 'false'),
	('Wilfred Purdy Hane', '+98 1-784-560-0592 x939', '1993-03-02', 'true'),
	('Taisha Botsford Prosacco', '+886 1-445-434-1056 x88281', '1983-03-09', 'true'),
	('Noemi Torp Crona I', '+248 823-903-0327 x06519', '1967-10-20', 'false'),
	('Msgr. Cary Hermiston Rogahn', '+56 1-323-842-4216 x08367', '1991-08-04', 'false'),
	('Pres. Tonie Herman Christiansen', '+269 609-654-2819 x2490', '1965-07-22', 'true'),
	('Rafael Wintheiser Skiles', '+242 241-166-5402', '2000-05-13', 'true'),
	('Mariano Dietrich Fritsch', '+249 1-709-138-3373 x7981', '1961-12-13', 'true'),
	('Emelia Kertzmann Mueller Sr.', '+855 1-116-590-8301', '1973-02-08', 'true'),
	('Sammy Jakubowski Ritchie', '+258 1-353-392-7468 x898', '1977-07-17', 'true'),
	('Danial Casper Cronin Esq.', '+423 744-115-2294 x411', '1998-03-24', 'true'),
	('Euna Dibbert Hackett', '+267 416.170.1105 x78400', '1976-05-16', 'false'),
	('Ricardo Nikolaus Stroman', '+380 (983) 622-9742 x602', '1966-05-23', 'false'),
	('Laverna Steuber Ratke', '+850 (821) 155-9540 x5624', '1967-05-10', 'true'),
	('Esperanza Pouros Goyette', '+1-671 437-777-8820 x871', '2003-10-21', 'true'),
	('Monica Jakubowski Harber', '+90 851-177-0919', '1980-05-22', 'true'),
	('Mr. Cherelle Legros Schinner', '+688 693.012.7304 x93688', '1971-06-13', 'true');
INSERT INTO flights (price, meal_included, flight_duration,  departure_time, aircompany_id,  departure_airport_id, arrival_airport_id) VALUES
	('1613', 'true', '2', '2023-04-25 08:51:33 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4138', 'true', '6', '2023-04-30 04:00:46 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2232', 'false', '7', '2023-04-28 05:41:35 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3119', 'false', '6', '2023-04-30 19:47:12 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('431', 'true', '9', '2023-04-25 05:44:14 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4985', 'true', '19', '2023-04-28 00:05:24 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4658', 'true', '4', '2023-04-27 12:07:47 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3063', 'true', '20', '2023-04-25 06:41:13 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3857', 'true', '19', '2023-04-29 15:03:48 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1106', 'true', '15', '2023-04-29 10:16:53 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1806', 'false', '4', '2023-04-28 22:24:17 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4810', 'true', '18', '2023-04-29 13:52:18 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4093', 'false', '9', '2023-04-29 22:58:22 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('578', 'true', '9', '2023-04-28 00:29:49 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1581', 'true', '15', '2023-05-01 19:06:40 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1886', 'false', '18', '2023-04-26 21:00:35 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2645', 'false', '2', '2023-04-29 23:48:16 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4847', 'false', '18', '2023-05-01 01:46:04 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2288', 'false', '5', '2023-05-01 09:36:05 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2869', 'false', '4', '2023-04-27 01:35:41 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3522', 'true', '8', '2023-04-25 21:57:43 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2673', 'false', '16', '2023-04-25 00:54:25 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2928', 'true', '5', '2023-04-25 22:18:56 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('624', 'false', '16', '2023-04-30 03:48:22 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2786', 'false', '11', '2023-04-28 01:34:16 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('693', 'false', '3', '2023-04-29 10:13:05 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2773', 'true', '13', '2023-04-26 20:12:34 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1922', 'true', '17', '2023-04-29 04:54:41 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1280', 'true', '8', '2023-04-26 02:13:16 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('252', 'true', '2', '2023-04-27 20:46:31 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('175', 'true', '7', '2023-04-30 07:36:40 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2948', 'false', '8', '2023-04-29 00:20:50 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1889', 'false', '8', '2023-05-01 20:18:59 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2026', 'false', '9', '2023-04-29 10:46:16 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1157', 'true', '4', '2023-04-29 12:50:58 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4477', 'false', '19', '2023-04-30 18:23:32 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3907', 'true', '17', '2023-04-29 02:17:29 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4865', 'false', '19', '2023-04-29 06:54:16 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1682', 'true', '6', '2023-04-28 11:13:53 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3834', 'true', '1', '2023-05-01 18:56:52 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3133', 'true', '4', '2023-04-30 14:36:28 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2244', 'true', '15', '2023-05-01 22:10:01 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4074', 'true', '3', '2023-04-26 13:30:16 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3185', 'false', '19', '2023-05-01 04:23:15 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('674', 'false', '5', '2023-04-26 16:34:32 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1496', 'false', '5', '2023-04-30 02:26:09 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4297', 'false', '12', '2023-05-01 14:00:26 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('551', 'true', '15', '2023-05-01 08:15:49 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2592', 'false', '20', '2023-04-26 19:50:39 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2425', 'false', '13', '2023-04-29 03:20:40 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2940', 'true', '14', '2023-04-29 04:55:04 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3162', 'false', '10', '2023-04-29 11:22:58 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2079', 'true', '2', '2023-05-01 10:04:00 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3870', 'true', '10', '2023-04-25 15:28:51 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1499', 'false', '3', '2023-04-27 18:54:17 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3144', 'false', '1', '2023-04-27 01:30:01 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('502', 'true', '10', '2023-04-27 08:53:11 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3395', 'false', '3', '2023-04-27 10:18:16 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2743', 'false', '7', '2023-04-28 01:40:53 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('407', 'true', '6', '2023-04-29 19:31:27 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3188', 'true', '19', '2023-04-26 08:25:01 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2183', 'true', '16', '2023-04-25 07:09:54 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4357', 'true', '20', '2023-04-27 22:45:54 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3381', 'false', '1', '2023-05-01 13:11:24 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1264', 'true', '17', '2023-04-27 12:48:18 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('269', 'false', '15', '2023-04-25 02:59:15 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3254', 'false', '5', '2023-04-30 19:15:25 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1157', 'false', '18', '2023-04-26 03:10:22 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4070', 'false', '9', '2023-05-01 21:08:34 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3384', 'true', '6', '2023-05-01 01:24:17 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2799', 'false', '2', '2023-04-28 06:50:51 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3221', 'true', '7', '2023-04-29 09:30:32 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('920', 'true', '3', '2023-04-25 22:25:06 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1285', 'true', '5', '2023-04-30 16:32:55 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('871', 'true', '3', '2023-04-25 12:09:03 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2896', 'false', '6', '2023-04-27 18:08:05 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2149', 'true', '16', '2023-05-01 09:17:58 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2143', 'true', '2', '2023-04-30 14:27:27 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3823', 'true', '15', '2023-04-27 20:09:15 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2580', 'false', '9', '2023-04-27 05:09:21 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('785', 'true', '11', '2023-04-29 09:37:09 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2608', 'true', '5', '2023-04-25 23:02:01 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2702', 'true', '13', '2023-05-01 16:18:55 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1978', 'false', '10', '2023-04-30 05:24:07 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3996', 'false', '18', '2023-04-26 01:47:53 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4324', 'false', '5', '2023-04-28 23:04:14 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4312', 'false', '11', '2023-04-29 08:25:06 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4733', 'false', '8', '2023-04-28 06:43:46 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3043', 'false', '2', '2023-04-30 18:28:40 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1554', 'false', '15', '2023-04-26 00:20:32 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('1222', 'false', '18', '2023-04-26 11:39:37 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4903', 'false', '10', '2023-05-01 03:54:32 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4201', 'false', '8', '2023-04-26 00:34:48 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('58', 'true', '10', '2023-04-29 18:00:41 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('893', 'true', '8', '2023-04-29 01:28:13 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('3869', 'true', '12', '2023-04-28 11:56:41 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4173', 'true', '12', '2023-04-27 06:06:01 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('4095', 'false', '19', '2023-05-01 02:44:29 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('2369', 'true', '8', '2023-04-29 18:10:57 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('614', 'false', '9', '2023-04-30 07:55:40 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1)),
	('73', 'true', '9', '2023-05-01 05:24:18 +0300', (SELECT id FROM aircompanies ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1), (SELECT id FROM airports ORDER BY random() LIMIT 1));
INSERT INTO trips (departure_flight_id, hotel_id, meal) VALUES
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Room Only' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Full Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Ultra All Inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'All inclusive' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Half Board plus' ),
	((SELECT id from flights where flights.departure_time != (SELECT max(departure_time) from flights) ORDER BY random() LIMIT 1), (SELECT id FROM hotels ORDER BY random() LIMIT 1),  'Bed and Breakfast' );
UPDATE trips SET arrival_flight_id = (SELECT id from flights where flights.departure_time > (SELECT departure_time FROM flights where flights.id = trips.departure_flight_id) ORDER BY random() LIMIT 1),
        departure_date = (SELECT departure_time from flights where flights.id = trips.departure_flight_id );
UPDATE trips SET arrival_date = (SELECT departure_time from flights where flights.id = trips.arrival_flight_id );
INSERT INTO workers (full_name, phone, birthday_date, salary) VALUES
	('Art Casper Littel DDS', '+1 1-544-292-2051 x36278', '1959-07-04', 3130),
	('Hugh Gerhold Mitchell I', '+994 837-727-5135 x78813', '2003-08-14', 3828),
	('Tracey Kertzmann Baumbach', '+7 (310) 110-0304 x86614', '1993-03-05', 4113),
	('Yelena Cummings Nolan', '+251 1-319-189-5263 x13513', '1974-05-07', 2660),
	('Hector Raynor Haley', '+685 904.317.1208', '1996-07-05', 2520),
	('Mr. Bertha Beier McLaughlin', '+33 525-572-1347 x6260', '2000-10-03', 1285),
	('Sandy Brown Jast', '+39 700-611-8700 x36755', '1998-02-10', 2855),
	('Chuck Feest Mann', '+229 1-646-308-5863 x961', '1987-12-27', 3480),
	('Wilda Buckridge Bosco', '+767 652.506.1573', '1977-02-04', 3897),
	('Dallas Macejkovic Wolff', '+64 (228) 730-8178 x0471', '1971-01-06', 3824),
	('Jordan Watsica DAmore', '+39 782.520.9275 x66872', '1972-09-05', 2336),
	('Sonny Rodriguez Ondricka', '+976 (738) 926-9341 x36586', '1991-03-06', 4766),
	('Shaun Stanton Wiegand', '+1-787 419.990.1626', '1994-04-17', 3836),
	('Mr. Gil Bradtke Schmitt', '+244 (439) 071-0166 x72406', '2005-04-24', 2902),
	('Tisa Boyer Murray', '+263 565-816-5553 x0059', '1976-12-09', 2652),
	('Sandi Mraz OKeefe', '+886 1-913-877-1198 x8146', '1968-08-10', 4287),
	('Nickolas Pfannerstill Hackett', '+297 (625) 430-2392 x5818', '1969-02-07', 4895),
	('Charita Kovacek Nicolas', '+227 1-772-848-3575 x3930', '1989-08-13', 2626),
	('Oliver Sauer Lynch', '+964 646.421.5848 x820', '1999-09-14', 119),
	('Mrs. Kyla Muller Wiza', '+36 364-018-7421 x08223', '1964-05-31', 1164),
	('Chet Bauch Wuckert', '+674 1-809-873-2233 x595', '1984-04-15', 1075),
	('Adella Jones Runolfsson', '+51 1-886-682-3520', '1975-08-21', 1017),
	('Msgr. Lesley Ritchie Rice', '+231 831.904.5010 x67100', '1980-06-24', 2970),
	('Raphael Trantow McKenzie', '+962 1-453-049-9940 x014', '1997-03-04', 2533),
	('Rudolph Treutel Mertz', '+680 857.563.4714 x14809', '1969-05-21', 110),
	('Candance Yost Hills', '+45 (900) 392-1959 x374', '1967-10-20', 4449),
	('Freeman Stiedemann Hackett', '+230 842.458.5447', '1979-11-11', 395),
	('Josie Heller Fisher', '+268 1-815-079-9877 x885', '1976-05-31', 932),
	('Blaine Treutel Padberg', '+94 132.300.9123', '1990-06-02', 304),
	('Derick Parker Bayer', '+505 (613) 913-4641 x721', '1966-10-01', 4562),
	('Jenee Koelpin Weimann', '+298 (141) 137-7206 x5030', '2003-07-25', 3308),
	('Hertha Denesik Crona', '+269 (696) 610-5842', '1990-02-09', 1778),
	('Ginette Kunze Doyle PhD', '+255 403.880.4974 x79300', '1980-09-26', 1030),
	('Susy Gorczany Little', '+670 (857) 952-1257 x7474', '1963-12-26', 4523),
	('Roberto Hamill Quitzon', '+373 903.617.4565', '1992-04-12', 3616),
	('Miss Hershel Wyman Kautzer', '+41 942-398-8494 x1971', '1980-10-08', 4897),
	('The Hon. Roy Gleichner Stanton', '+688 301.079.2511 x61295', '1974-06-09', 1679),
	('Madalyn Labadie Pfeffer', '+689 1-700-016-4566', '1988-12-20', 3253),
	('Moises Schneider Kessler I', '+253 881-303-9406', '1969-10-01', 1848),
	('Christopher Gibson Strosin', '+358 (707) 959-5610 x4760', '1969-09-04', 4549),
	('Alva Russel Renner', '+261 1-859-294-4818 x182', '1980-02-08', 2131),
	('Carmon Bartoletti Bode', '+30 1-307-016-4134 x5112', '1975-04-01', 260),
	('Enid Durgan Stracke', '+973 (887) 969-0302 x626', '1970-06-22', 3990),
	('Ji Leffler Nicolas', '+269 754-190-0286 x222', '1979-05-25', 3157),
	('Rep. Samuel Ernser Orn', '+503 462.781.9715 x02649', '1963-04-27', 3031),
	('Mr. Roselee Goodwin Kshlerin', '+48 776-735-1520', '1995-05-10', 2543),
	('Sydney Little Larkin', '+7-6 1-464-293-2763', '1995-03-07', 3312),
	('Ervin MacGyver Goyette DC', '+356 195.700.6039', '1980-01-30', 709),
	('Dovie Corwin Runolfsson PhD', '+675 765-316-2058 x898', '1970-12-24', 1295),
	('Cliff Bashirian Zieme VM', '+855 (417) 222-1145', '1986-12-25', 2287),
	('Trinity Schinner Borer', '+355 841.591.0203 x70571', '1971-10-06', 4312),
	('Vincenza Sipes Stamm', '+222 754.760.0233 x19653', '1987-07-26', 4732),
	('Rona Reilly Christiansen', '+64 (856) 820-8887 x574', '1998-03-25', 1961),
	('Luciano Mayert Cartwright', '+58 1-730-400-9942 x06370', '1978-06-15', 100),
	('Chet Bogan Konopelski', '+91 1-442-752-7775 x17840', '1978-07-29', 4121),
	('Luis Herzog Glover', '+880 1-258-609-9372', '1997-04-10', 2831),
	('Darcie Erdman Frami', '+84 (383) 905-1485', '1962-12-15', 2577),
	('Santos Wyman Ward', '+886 212-892-0703 x09267', '1987-09-16', 4864),
	('Mora Hegmann Boehm', '+61 1-432-776-9930 x168', '1965-04-17', 4600),
	('Delois Shanahan Barton', '+1-242 1-658-051-2875 x6840', '1998-12-12', 1148),
	('Joseph Schroeder Dicki', '+98 163-901-7497', '1961-05-07', 1895),
	('Clifford Champlin Thiel', '+216 573-934-7898 x689', '1975-12-08', 3245),
	('Toney Kutch Hammes', '+261 325-915-6606 x5488', '2004-07-09', 917),
	('Msgr. Alene Anderson Ullrich', '+594 (934) 072-8250 x74792', '1976-03-10', 1199),
	('Mr. Larita Lehner Hodkiewicz', '+674 (543) 829-3234', '1997-02-05', 2147),
	('Sen. Clifford Schmidt Emard', '+224 702.082.1268 x6283', '1969-12-03', 566),
	('Julian Ward Baumbach', '+49 (462) 467-7411 x02054', '1961-03-01', 2271),
	('Jeannine Schoen Anderson', '+961 920.015.0631', '1976-10-30', 4667),
	('Issac Lemke Grant', '+244 496.644.3829', '1963-04-19', 1742),
	('Foster Halvorson Lueilwitz', '+381 (177) 590-5182 x9766', '1967-02-19', 4345),
	('Milton Klocko Olson', '+596 (933) 833-1768 x2467', '1984-08-30', 2122),
	('Terrilyn Ratke Schuster', '+220 503-015-0209 x47808', '1984-07-13', 2713),
	('Cesar Dietrich Considine', '+506 1-370-456-0786', '2004-06-04', 3110),
	('Logan Casper Sauer', '+351 (216) 882-3938 x7494', '1991-01-02', 70),
	('Jeanie Cronin Emmerich', '+62 422.859.0333', '1973-12-27', 1836),
	('George Spinka Volkman', '+267 553-235-1619 x20946', '1977-04-02', 269),
	('Isaias Bailey Franecki', '+30 678-946-0466 x019', '1962-12-18', 3896),
	('Kendall Wehner Fadel', '+677 581-143-8087 x442', '1987-08-12', 1564),
	('Rep. Kirsten Graham Little', '+850 (801) 566-4457 x806', '1958-10-21', 1377),
	('Ilene Ferry Durgan', '+52 1-313-140-0918', '1975-12-29', 3268),
	('Ellen Schulist Rice', '+241 (342) 296-3812 x65530', '1978-01-30', 1940),
	('Augustus Lowe Boyle IV', '+62 991.872.2949 x5329', '1984-10-10', 1090),
	('Laraine Paucek Douglas', '+43 974-169-3922 x069', '1994-06-13', 1551),
	('Tobias Towne Bogan', '+253 391.007.1957 x26773', '1999-09-27', 4732),
	('Ms. Christopher OConner Windler', '+227 492-346-7096', '1994-01-11', 1431),
	('Toccara Simonis Batz', '+245 (891) 078-7281 x172', '1985-11-06', 620),
	('Willy Reynolds Jenkins', '+242 860.376.9074 x97953', '1959-09-25', 48),
	('Larissa Mann Bartell', '+675 (884) 996-3304 x09953', '2003-03-20', 2949),
	('Clarita Bogisich Lockman', '+679 712.212.7895', '1980-09-16', 1722),
	('Prof. Sammy Collins Rath', '+688 1-648-593-0820', '1983-06-15', 3216),
	('Amb. Tory Turner Frami', '+359 1-367-381-9066 x3885', '1990-03-27', 1495),
	('Mikel Donnelly Barton', '+36 1-731-751-1757', '1998-09-28', 3284),
	('Enoch Hills McCullough', '+690 885-906-1434 x839', '1958-11-28', 4943),
	('Stephania Price Crist', '+240 1-389-200-3339 x1243', '1988-12-08', 2095),
	('Elwood Walker Wintheiser', '+994 (483) 458-7551 x2862', '1965-03-16', 3853),
	('Herb Schaden Kshlerin', '+236 1-603-575-3654 x344', '1961-05-30', 1871),
	('Mr. Corrinne Rosenbaum Mayert', '+299 494.058.1194 x67227', '1999-06-07', 178),
	('Norman Conroy Heathcote', '+299 1-245-948-8237 x805', '1969-12-29', 4361),
	('Davis Doyle Graham Sr.', '+257 170.075.5255 x71065', '1985-08-13', 4450),
	('Johnnie Leffler Zieme', '+855 679-349-9366 x4605', '1975-04-19', 878),
	('Johnson Dare Skiles', '+64 654-500-9921', '1967-05-25', 2662);
